### ISSUE TITLE
执行mongoshake-stat命令但是报错

### ISSUE THREAD

**Issue by zeusYi** [alibaba/MongoShake#135]
[root@ftp bin]# ./mongoshake-stat --port=9100 --host=127.0.0.1
Traceback (most recent call last):
  File "./mongoshake-stat", line 36, in __get_json
    resp = urllib2.urlopen("http://%s:%s/%s" % (host, port, spec)).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
failed
Traceback (most recent call last):
  File "./mongoshake-stat", line 124, in <module>
    details = get_json("repl")
  File "./mongoshake-stat", line 44, in get_json
    return __get_json(host, port, spec)
  File "./mongoshake-stat", line 40, in __get_json
    __crash("failed")
  File "./mongoshake-stat", line 49, in __crash
    exit(-1)
  File "/usr/lib64/python2.7/site.py", line 364, in __call__
    raise SystemExit(code)
SystemExit: -1

检查端口是活动的
[root@ftp bin]# netstat -an|grep 9100
tcp6       0      0 :::9100                 :::*                    LISTEN

**Comment by vinllen** [comment]
你手动curl一下9100端口 看看是否有返回。`curl 127.0.0.1:9100/repl`

**Comment by zeusYi** [comment]
@vinllen 多谢已经解决了

**Comment by liuqy95** [comment]
这个怎么解决的，我的也报错

**Comment by liuqy95** [comment]
Failed connect to 127.0.0.1:9100; Connection refused

**Comment by vinllen** [comment]
目前只有进入增量阶段这个端口才会开放
