### ISSUE TITLE
mongoshake 启动故障

### ISSUE THREAD

**Issue by wwz801226** [alibaba/MongoShake#254]
无论使用二进制包还是自行编译安装，最终启动都出现这个报错

[root@cns-vs-k0085 bin]# ./collector.linux -conf=../conf/collector.conf
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x918d92]

goroutine 1 [running]:
main.handleExit()
	/usr/local/mongo-shake/src/mongoshake/collector/main/collector.go:282 +0x89
panic(0x9da840, 0xf7eda0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
mongoshake/collector.(*ReplicationCoordinator).selectSyncMode(0xc4201bc200, 0xc4201be04c, 0x3, 0x1, 0x1, 0x65b, 0x0, 0xc4201cca80)
	/usr/local/mongo-shake/src/mongoshake/collector/replication.go:194 +0x322
mongoshake/collector.(*ReplicationCoordinator).Run(0xc4201bc200, 0xc4201bc2c0, 0xc4201afd70)
	/usr/local/mongo-shake/src/mongoshake/collector/replication.go:55 +0x297
main.startup()
	/usr/local/mongo-shake/src/mongoshake/collector/main/collector.go:111 +0x487
main.main()
	/usr/local/mongo-shake/src/mongoshake/collector/main/collector.go:84 +0x681

**Comment by vinllen** [comment]
给一下版本号

**Comment by wwz801226** [comment]
> 给一下版本号

mongoshake 版本号 2.0.8
go 版本号  go version go1.9 linux/amd64

**Comment by vinllen** [comment]
这个不应该有问题，是不是你改了代码导致的，看看sync_mode这个配置

**Comment by wwz801226** [comment]
代码肯定没动，最多就是修改配置文件。。
果然和这个配置项有关系
sync_mode = oplog 这个可以启动
但是
sync_mode = all  这样配置会报错

**Comment by wwz801226** [comment]
[2019/10/31 15:08:10 CST] [WARN] [ckpt.(*MongoCheckpoint).Get:162] Reload ckpt find context fail. not authorized on admin to execute command { find: "ckpt_default", filter: { name: "shard3" }, skip: 0, limit: 1, batchSize: 1, singleBatch: true }
[2019/10/31 15:08:10 CST] [WARN] [ckpt.(*MongoCheckpoint).Get:162] Reload ckpt find context fail. not authorized on admin to execute command { find: "ckpt_default", filter: { name: "shard2" }, skip: 0, limit: 1, batchSize: 1, singleBatch: true }
[2019/10/31 15:08:10 CST] [CRIT] [collector.(*OplogSyncer).poll:328] Acquire the existing checkpoint from remote[ckpt_default] failed !
[2019/10/31 15:08:10 CST] [WARN] [ckpt.(*MongoCheckpoint).Get:162] Reload ckpt find context fail. not authorized on admin to execute command { find: "ckpt_default", filter: { name: "shard1" }, skip: 0, limit: 1, batchSize: 1, singleBatch: true }
[2019/10/31 15:08:10 CST] [WARN] [collector.(*OplogSyncer).start:169] Oplog syncer polling yield. master:true, yield:6000ms
[2019/10/31 15:08:10 CST] [CRIT] [collector.(*OplogSyncer).poll:328] Acquire the existing checkpoint from remote[ckpt_default] failed !
[2019/10/31 15:08:10 CST] [CRIT] [collector.(*OplogSyncer).poll:328] Acquire the existing checkpoint from remote[ckpt_default] failed !

**Comment by wwz801226** [comment]
目前可以启动了，上面的报错是账号权限问题

但经过测试有个问题

sync_mode = oplog

这个我即便设置成增量模式，当我同步到一个没有这个库的环境，还是会把源端的所有数据都同步过来

**Comment by vinllen** [comment]
你上面第一次反馈panic的时候这个sync_mode就已经设置了？这个看起来不是一个问题。mongodb的insert操作会自动插入db，跟目的端原来有没有没有关系。

**Comment by wwz801226** [comment]
对的，第一次sync_mode 已经设置了oplog
