### ISSUE TITLE
从分片集群导入kafka提示no reachable servers

### ISSUE THREAD

**Issue by dx8439** [alibaba/MongoShake#309]
从分片集群导入kafka提示no reachable servers，副本集就没事。检查分片成功，但是到了kafka那就提示没有可访问的服务器。

kafka处配置：
tunnel = kafka
tunnel.address = test@10.3.4.176:9092
tunnel.message = json
context.storage = database
context.storage.url = mongodb://10.3.4.169:28018
context.storage.db = mongoshake
context.storage.collection = ckpt_default

启动错误提示信息：
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.169:28019 successfully
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://10.3.4.169:28019
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.169:28019 successfully
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://10.3.4.169:28019
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.168:28019 successfully
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://10.3.4.168:28019
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.168:28019 successfully
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://10.3.4.168:28019
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.167:28019 successfully
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://10.3.4.167:28019
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.167:28019 successfully
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://10.3.4.167:28019
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/collector.(*ReplicationCoordinator).Run:67) start running with mode[oplog]
[15:43:16 CST 2020/03/24] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://10.3.4.169:28018 successfully
[15:43:27 CST 2020/03/24] [CRIT] (mongoshake/common.NewMongoConn:57) Connect to test@10.3.4.176:9092 failed. no reachable servers
[15:43:27 CST 2020/03/24] [CRIT] (mongoshake/collector.NewDDLManager:62) Connect toUrl[mongodb://10.3.4.169:28018] error[no reachable servers].
[15:43:27 CST 2020/03/24] [CRIT] (mongoshake/common.NewMongoConn:57) Connect to test@10.3.4.176:9092 failed. no reachable servers
[15:43:27 CST 2020/03/24] [CRIT] (mongoshake/collector.NewDDLManager:62) Connect toUrl[mongodb://10.3.4.169:28018] error[no reachable servers].
panic: Connect toUrl[mongodb://10.3.4.169:28018] error[no reachable servers]. [recovered]
	panic: Connect toUrl[mongodb://10.3.4.169:28018] error[no reachable servers].

goroutine 1 [running]:
main.handleExit()
	/home/zhuzhao.cx/MongoShake/src/mongoshake/collector/main/collector.go:299 +0x89
panic(0x995340, 0xc420430700)
	/home/zhuzhao.cx/go/src/runtime/panic.go:502 +0x229
vendor/github.com/vinllen/log4go.Crashf(0xa90c49, 0x1c, 0xc42020f8e0, 0x2, 0x2)
	/home/zhuzhao.cx/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector.NewDDLManager(0xc420210d80, 0x0)
	/home/zhuzhao.cx/MongoShake/src/mongoshake/collector/ddloplog.go:62 +0x26c
mongoshake/collector.(*ReplicationCoordinator).startOplogReplication(0xc420198320, 0xc4203aeb70, 0xc4203aeba0, 0xd, 0xc420289f78)
	/home/zhuzhao.cx/MongoShake/src/mongoshake/collector/replication.go:407 +0x1f0
mongoshake/collector.(*ReplicationCoordinator).Run(0xc420198320, 0xc420198320, 0x3)
	/home/zhuzhao.cx/MongoShake/src/mongoshake/collector/replication.go:100 +0x598
main.startup()
	/home/zhuzhao.cx/MongoShake/src/mongoshake/collector/main/collector.go:102 +0x2d2
main.main()
	/home/zhuzhao.cx/MongoShake/src/mongoshake/collector/main/collector.go:83 +0x621
[root@localhost mongo-shake]# 
[root@localhost mongo-shake]# 
[root@localhost mongo-shake]# ./collector.linux -conf=collector.conf -verbose
Conf.Options check failed: config server url should be configured when transfer from mongo sharding

**Comment by vinllen** [comment]
panic: Connect toUrl[mongodb://10.3.4.169:28018] error[no reachable servers].
这个应该是你的这个库访问不上导致的，确定可以访问吗？

**Comment by dx8439** [comment]
这个是我cs端，只不过我只做了一个节点，我的防火墙关了，selinux也关了
