### ISSUE TITLE
feature-2.1-unstable-问题：collector运行过程中报错unsupported u move chunk oplog 

### ISSUE THREAD

**Issue by chaoxxx** [alibaba/MongoShake#314]
## 软件版本
* MongoShake[feature-2.1-unstable]
* MongoDB[v4.0.13]

## 问题描述
因为要一直打开balance，所以尝试使用*MongoShake[feature-2.1-unstable]*版本，今天在使用过程中，collector突然报错，且无法正常启动。
```
[root@vm3 MongoShake]# bin/collector.linux -conf=conf/collector.conf
[16:33:34 CST 2020/03/27] [CRIT] (mongoshake/collector.(*MoveChunkValue).addMoveChunk:495) unsupported u move chunk oplog[{42F88D20-33EF-4074-9D45-7325025D604820200327161659 mysync.realtime_air} Timestamp(1585296975, 8036)]
panic: unsupported u move chunk oplog[{42F88D20-33EF-4074-9D45-7325025D604820200327161659 mysync.realtime_air} Timestamp(1585296975, 8036)]

goroutine 356 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xaf9bb5, 0x26, 0xc0048519b0, 0x3, 0x3)
	/root/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xe4
mongoshake/collector.(*MoveChunkValue).addMoveChunk(0xc00496b060, 0xc0002d16e8, 0x6, 0x9f5060, 0xc009254170, 0xc008ce5e20, 0x13, 0xc009041680)
	/root/MongoShake/src/mongoshake/collector/movechunk.go:495 +0x6ad
mongoshake/collector.(*MoveChunkManager).BarrierOplog(0xc0002dd7c0, 0xc0002d16e8, 0x6, 0xc009041680, 0xc000060000, 0x0, 0x0)
	/root/MongoShake/src/mongoshake/collector/movechunk.go:234 +0x12e9
mongoshake/collector.moveChunkBarrier(0xc000096000, 0xc009041680, 0x1e77ee98e10000)
	/root/MongoShake/src/mongoshake/collector/batcher.go:252 +0x90
mongoshake/collector.(*Batcher).filterAndBlockMoveChunk(0xc000106000, 0xc00923a000, 0x100, 0x100, 0xc0001ee000, 0x0, 0x0, 0x0, 0xc0001c0000, 0x0)
	/root/MongoShake/src/mongoshake/collector/batcher.go:163 +0x6de
mongoshake/collector.(*OplogSyncer).startBatcher.func1()
	/root/MongoShake/src/mongoshake/collector/syncer.go:185 +0xbd
vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop.func1(0xc0010f2480)
	/root/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:19 +0x25
created by vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop
	/root/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:17 +0x3f
```

这个是由于什么原因导致的呢？我需要如何修复？

**Comment by chaoxxx** [comment]
@vinllen

**Comment by vinllen** [comment]
你这个是2.1的非稳定版本，升级到2.4走change stream吧

**Comment by chaoxxx** [comment]
刚刚看到了新发布的2.4版本。我这周末试一下。
