### ISSUE TITLE
panic: interface conversion: interface {} is []bson.M, not []interface {}

### ISSUE THREAD

**Issue by huntlyroad** [alibaba/MongoShake#329]
Hi, We ran into a problem with following setup:

Mongoshake: 2.4.1
source Mongodb: 4.0.18
dest Mongodb: 3.6.12
collection is sharded and balancer is enabled
DDL is disabled and sync source is change_stream.

When insert into source collections, mongoshake paniced with following message

`panic: interface conversion: interface {} is []bson.M, not []interface {}`

Here is the INFO log before this error

```
[17:31:13 CST 2020/04/21] [INFO] (mongoshake/executor.(*Executor).execute:90) Replay-0 run DDL with metadata[admin] in db[map[]], firstLog: {"ts":6817993276520399226,"op":"c","g":"","ns":"admin.$cmd","o":[{"Name":"applyOps","Value":[{"ns":"__test.new2","o":[{"Name":"_id","Value":"5e9e60c3d7feca7dc6bcd96a"},{"Name":"id","Value":40072},{"Name":"name","Value":"name_40072_1587437763179"},{"Name":"meetingId","Value":"mid_40072_1587437763179"},{"Name":"roomNum","Value":"roomNum_40072_1587437763179"},{"Name":"time","Value":"time_40072_1587437763179"},{"Name":"country","Value":"country_40072_1587437763179"},{"Name":"sn","Value":"7762065935"},{"Name":"cl_src","Value":"cl1"}],"o2":null,"op":"i"},{"ns":"__test.new2","o":[{"Name":"_id","Value":"5e9e60c3d7feca7dc6bcde65"},{"Name":"id","Value":4347},{"Name":"name","Value":"name_4347_1587437763379"},{"Name":"meetingId","Value":"mid_4347_1587437763379"},{"Name":"roomNum","Value":"roomNum_4347_1587437763379"},{"Name":"time","Value":"time_4347_1587437763379"},{"Name":"country","Value":"country_4347_1587437763379"},{"Name":"sn","Value":"7762065935"},{"Name":"cl_src","Value":"cl1"}],"o2":null,"op":"i"}]}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}
[17:31:13 CST 2020/04/21] [INFO] (mongoshake/executor.RunCommand:610) RunCommand run DDL with type[applyOps]
```

And this is the stack trace:

```
goroutine 826 [running]:
mongoshake/executor.RunCommand(0x18a1db5, 0x5, 0x18a06a0, 0x8, 0xc421c94b40, 0xc4204e21c0, 0x0, 0x0)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/executor/db_writer.go:646 +0x159f
mongoshake/executor.(*BulkWriter).doCommand(0xc4201e4018, 0x18a1db5, 0x5, 0xc421eecd80, 0xc4201c2238, 0x1, 0x1, 0x2, 0x2)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/executor/db_writer.go:395 +0x13d
mongoshake/executor.(*Executor).execute(0xc4200ae100, 0xc4201df3b0, 0xc4201c2230, 0x1)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/executor/operation.go:92 +0xc54
mongoshake/executor.(*Executor).doSync(0xc4200ae100, 0xc4201c2230, 0x1, 0x1, 0xc4201e61e0, 0x11daab0)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/executor/executor.go:236 +0xfd
mongoshake/executor.(*Executor).start(0xc4200ae100)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/executor/executor.go:212 +0x84
created by mongoshake/executor.(*BatchGroupExecutor).Start
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/executor/executor.go:69 +0xb6
```

Apparently mongos doesn't allow applyOps operation. How can I solve this?

**Comment by vinllen** [comment]
Thanks for your report, this is a bug and I'll fix it tomorrow.

**Comment by vinllen** [comment]
please try v2.4.2

**Comment by huntlyroad** [comment]
Hi @vinllen ,

Thank you for prompt fix.
Actually I have bypassed this error earlier but another critical error happens:

```
[13:58:38 CST 2020/04/22] [CRIT] (mongoshake/executor.(*Executor).execute:111) Replayer-0, executor-0, oplog for namespace[admin.$cmd] op[c] failed. error type[*mgo.QueryError] error[no such cmd: applyOps], logs number[1], firstLog: {"ts":6817993276520399226,"op":"c","g":"","ns":"admin.$cmd","o":[{"Name":"applyOps","Value":[{"ns":"__test.new2","o":[{"Name":"_id","Value":"5e9e60c3d7feca7dc6bcd96a"},{"Name":"id","Value":40072},{"Name":"name","Value":"name_40072_1587437763179"},{"Name":"meetingId","Value":"mid_40072_1587437763179"},{"Name":"roomNum","Value":"roomNum_40072_1587437763179"},{"Name":"time","Value":"time_40072_1587437763179"},{"Name":"country","Value":"country_40072_1587437763179"},{"Name":"sn","Value":"7762065935"},{"Name":"cl_src","Value":"colo1"}],"o2":null,"op":"i"},{"ns":"__test.new2","o":[{"Name":"_id","Value":"5e9e60c3d7feca7dc6bcde65"},{"Name":"id","Value":4347},{"Name":"name","Value":"name_4347_1587437763379"},{"Name":"meetingId","Value":"mid_4347_1587437763379"},{"Name":"roomNum","Value":"roomNum_4347_1587437763379"},{"Name":"time","Value":"time_4347_1587437763379"},{"Name":"country","Value":"country_4347_1587437763379"},{"Name":"sn","Value":"7762065935"},{"Name":"cl_src","Value":"colo1"}],"o2":null,"op":"i"}]}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}
```

The actual error is:
`
[*mgo.QueryError] error[no such cmd: applyOps]
`

I understand this happens because applyOps is an internal command and is not available on mongos. I don't know if it's just related to my setup (see above) or do I need to do anything to avoid this?

I am not sure why I get applyOps command from change_stream. I used mongoshake with oplogs for a long time and worked very well.

**Comment by vinllen** [comment]
1. applyOps is disabled by MongoS so if the target side is sharding, this error raised.
2. actually, what you currently use is still 'oplog' not 'change_stream', check the `incr_sync.mongo_fetch_method` and your current checkpoint. In change stream mode, applyOps won't appear because of almost all DDL except the `dropDatabase` and `drop` are filtered.

You can disable DDL: set `filter.ddl_enable = false` so that all DDL including applyOps will be filtered.

**Comment by huntlyroad** [comment]
Hi, @vinllen 

I have checked 
`incr_sync.mongo_fetch_method` is `change_stream`
`filter.ddl_enable = false` is set

But that error still happens, So I dig into code to see what happened.

I captured this is the original oplog from syncer.deserializer after parsed by `ConvertEvent2Oplog`.

```json
{
   "ts":6818432097623998466,
   "op":"i",
   "g":"",
   "ns":"__test.new2",
   "o":[
      {
         "Name":"_id",
         "Value":"5e9fefde106eeec7613aa536"
      },
      {
         "Name":"id",
         "Value":300
      },
      {
         "Name":"name",
         "Value":"name_300_1587539934766"
      },
      {
         "Name":"meetingId",
         "Value":"mid_300_1587539934766"
      },
      {
         "Name":"roomNum",
         "Value":"roomNum_300_1587539934766"
      },
      {
         "Name":"time",
         "Value":"time_300_1587539934766"
      },
      {
         "Name":"country",
         "Value":"country_300_1587539934766"
      },
      {
         "Name":"sn",
         "Value":"9934343968"
      }
   ],
   "o2":null,
   "uk":null,
   "lsid":null,
   "fromMigrate":false
}
```

This looks completely normal but what is wired is that this block of code in batcher.go is called:

```go
if len(batcher.transactionOplogs) == 0 && batcher.previousFlush == false {
	// no transaction before, flush batchGroup
	batcher.transactionOplogs = append(batcher.transactionOplogs, batcher.previousOplog.Parsed)
	batcher.previousOplog = genericLog
	batcher.remainLogs = mergeBatch[i+1:]
	batcher.previousFlush = false
	return batcher.batchGroup, true, batcher.setLastOplog()
} else {
	// have transaction before, add previous
	batcher.transactionOplogs = append(batcher.transactionOplogs, batcher.previousOplog.Parsed)
}
```
By the name of the function, I can tell mongoshake is treating this op as a transaction. but it is not!
Then it triggers `batcher.gatherTransaction()` which apparently thinks `transaction oplogs should gather into an applyOps operation and add barrier here`

so this oplog ended up in this command now

```json
{
   "ts":6818432097623998466,
   "op":"c",
   "g":"",
   "ns":"admin.$cmd",
   "o":[
      {
         "Name":"applyOps",
         "Value":[
            {
               "ns":"__test.new2",
               "o":[
                  {
                     "Name":"_id",
                     "Value":"5e9fefde106eeec7613aa536"
                  },
                  {
                     "Name":"id",
                     "Value":300
                  },
                  {
                     "Name":"name",
                     "Value":"name_300_1587539934766"
                  },
                  {
                     "Name":"meetingId",
                     "Value":"mid_300_1587539934766"
                  },
                  {
                     "Name":"roomNum",
                     "Value":"roomNum_300_1587539934766"
                  },
                  {
                     "Name":"time",
                     "Value":"time_300_1587539934766"
                  },
                  {
                     "Name":"country",
                     "Value":"country_300_1587539934766"
                  },
                  {
                     "Name":"sn",
                     "Value":"9934343968"
                  },
               ],
               "o2":null,
               "op":"i"
            },
            {
               "ns":"__test.new2",
               "o":[
                  {
                     "Name":"_id",
                     "Value":"5e9fefde106eeec7613aa568"
                  },
                  {
                     "Name":"id",
                     "Value":0
                  },
                  {
                     "Name":"name",
                     "Value":"name_0_1587539934770"
                  },
                  {
                     "Name":"meetingId",
                     "Value":"mid_0_1587539934770"
                  },
                  {
                     "Name":"roomNum",
                     "Value":"roomNum_0_1587539934770"
                  },
                  {
                     "Name":"time",
                     "Value":"time_0_1587539934770"
                  },
                  {
                     "Name":"country",
                     "Value":"country_0_1587539934770"
                  },
                  {
                     "Name":"sn",
                     "Value":"9934343968"
                  },
               ],
               "o2":null,
               "op":"i"
            }
         ]
      }
   ],
   "o2":null,
   "uk":null,
   "lsid":null,
   "fromMigrate":false
}
```

I am not sure what is the logic there. Can you help me figure this out? If you need any further information, please leave me a note.

**Comment by vinllen** [comment]
@huntlyroad so your current question is the applyOps command should be filtered but actually not, right?

**Comment by huntlyroad** [comment]
@vinllen 还是中文清楚一点吧
我现在不知道为什么
`
if len(batcher.transactionOplogs) == 0 && batcher.previousFlush == false {
`
这个条件会满足，这个Flush是什么逻辑，因为看起来当这个条件满足时候，会append到`batcher.transactionOplogs`，如果我没理解错，这个应该只有transactions oplogs才会写入，但是我现在的oplog都是很简单的CRUD，并没有transactions，而且一旦mongoshake认为transactionOplogs不为空，又会触发`batcher.gatherTransaction()`，这使得一条简单的oplog变成了applyOps的操作，引发了错误。


补充一下我的debug过程：
首先我print出了每一条change stream拉出来的event，发现没有什么问题，没有发现applyOps，然后我就很奇怪这个applyOps的command是哪里来的
于是我打印出了deserilizer parsed 每一条从event 转换过来的oplogs，也没有发现问题
于是我怀疑是不是batcher那一块出了问题，
我发现`batcher.gatherTransaction()`被call了，而这个func会把oplogs打包成applyOps，导致了上述问题。
但是我再想接着debug就有一点困难了，因为我不知道设计上gatherTransaction()是什么情况下会触发，还有transactionlogs的len()为什么会不为0。
所以过来求助了。

**Comment by vinllen** [comment]
你这个时间戳的前后的oplog打印我看一下。这个时间戳的oplog应该不止一条吧？如果存在多条时间戳一样的oplog，mongoshake会合并成一条applyOps。
```
use local;
db.oplog.rs.find({"ts": 你上面的时间戳})
```

**Comment by vinllen** [comment]
这个问题后面还有疑问，钉钉找我好了，沟通效率高一些

**Comment by huntlyroad** [comment]
```javascript
{
	"ts" : Timestamp(1587539934, 2),
	"t" : NumberLong(7),
	"h" : NumberLong("-4488158393190183903"),
	"v" : 2,
	"op" : "i",
	"ns" : "__test.new2",
	"ui" : UUID("c3d6f342-36bd-4d4a-a3e5-9da8464a381d"),
	"wall" : ISODate("2020-04-22T07:18:54.839Z"),
	"lsid" : {
		"id" : UUID("5bc5dc04-4349-4e0b-9052-06d87f1d9e78"),
		"uid" : BinData(0,"C2ETZIu3FWqhEf1puHAy0TEEcmdiFwIH90Pml5etnxk=")
	},
	"txnNumber" : NumberLong(1),
	"stmtId" : 0,
	"prevOpTime" : {
		"ts" : Timestamp(0, 0),
		"t" : NumberLong(-1)
	},
	"o" : {
		"_id" : ObjectId("5e9fefde106eeec7613aa536"),
		"id" : 300,
		"name" : "name_300_1587539934766",
		"meetingId" : "mid_300_1587539934766",
		"roomNum" : "roomNum_300_1587539934766",
		"time" : "time_300_1587539934766",
		"country" : "country_300_1587539934766",
		"sn" : "9934343968",
	}
}
```
另一条batch起来的

```javascript
{
	"ts" : Timestamp(1587539934, 2),
	"t" : NumberLong(13),
	"h" : NumberLong("3480984673479611697"),
	"v" : 2,
	"op" : "i",
	"ns" : "__test.new2",
	"ui" : UUID("c3d6f342-36bd-4d4a-a3e5-9da8464a381d"),
	"wall" : ISODate("2020-04-22T07:18:54.833Z"),
	"lsid" : {
		"id" : UUID("9958d945-4ca4-42cb-904c-621cc39c9a00"),
		"uid" : BinData(0,"C2ETZIu3FWqhEf1puHAy0TEEcmdiFwIH90Pml5etnxk=")
	},
	"txnNumber" : NumberLong(1),
	"stmtId" : 0,
	"prevOpTime" : {
		"ts" : Timestamp(0, 0),
		"t" : NumberLong(-1)
	},
	"o" : {
		"_id" : ObjectId("5e9fefde106eeec7613aa568"),
		"id" : 0,
		"name" : "name_0_1587539934770",
		"meetingId" : "mid_0_1587539934770",
		"roomNum" : "roomNum_0_1587539934770",
		"time" : "time_0_1587539934770",
		"country" : "country_0_1587539934770",
		"sn" : "9934343968",
	}
}

```
发现时间戳确实是一样的

这是我的oplog.rs里找到的记录，确实也很正常。
钉钉要贴代码估计比较麻烦吧

**Comment by vinllen** [comment]
你这2个oplog是一个shard里面的吧？那应该本身就是事务，同一个shard只有事务才会产生2个时间戳一样的oplog

**Comment by vinllen** [comment]
看来这里需要修改一下，不能采用applyOps写入，而是应该封装成一个事务写入到目的端。

**Comment by huntlyroad** [comment]
@vinllen 是在两个不同的shard上的

**Comment by huntlyroad** [comment]
我就是奇怪为啥这两条会被当做事务处理

我是压测的时候发现的这个问题，写入是非常快的

**Comment by vinllen** [comment]
@huntlyroad 这个的确是目前程序处理的bug

**Comment by vinllen** [comment]
目前用oplog模式可以规避这个问题，change_stream对接从Mongos上拉取，而mongoshake判断事务的标准是2个ts一样，这个从mongos上拉取，2个不同的shard是可能存在一致的oplog，所以就有问题了。原来的oplog模式是从不同shard分开拉取，不会有问题。

**Comment by vinllen** [comment]
总结一下，目前需要改进的地方：
1. 不同shard拉取的oplog，即使ts一样，也不能当做一个事务。（**bug**）
2. 同一个shard拉取的oplog，即使是事务，也不能用applyOps写入。（**improve**）

**Comment by huntlyroad** [comment]
@vinllen 知道问题的根源就好了，我其实本来就是想试试change_stream拉取的效率，结果发现延迟有点大，所以本来就准备放弃changestream了，但是发现了这个问题还是想要先解决一下，谢谢你的帮助

**Comment by vinllen** [comment]
嗯嗯 感谢反馈 这个后面会处理掉的

**Comment by vinllen** [comment]
#370

**Comment by vinllen** [comment]
2.4.10版本已经发布，该issue将会合并，后续请关注#370
