### ISSUE TITLE
启动后多久会进入同步模式持久化数据？

### ISSUE THREAD

**Issue by muyuqingqiu** [alibaba/MongoShake#377]
我昨天第一次启动，今早看了下，进度显示100%，但是没有任何数据同步到目标端。
我删掉了目标端的 mongoshake db，重新启动，log如下，目前仍然没有数据同步过来

```
[00:59:58 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=131, filter=131, success=0, tps=0, ckpt_times=6, lsn_ckpt={6839918517630795777[1592542631, 1], 2020-06-19 00:57:11}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
[01:00:03 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=132, filter=132, success=0, tps=0, ckpt_times=6, lsn_ckpt={6839918517630795777[1592542631, 1], 2020-06-19 00:57:11}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
[01:00:08 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=132, filter=132, success=0, tps=0, ckpt_times=6, lsn_ckpt={6839918517630795777[1592542631, 1], 2020-06-19 00:57:11}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
[01:00:13 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=133, filter=133, success=0, tps=0, ckpt_times=6, lsn_ckpt={6839918517630795777[1592542631, 1], 2020-06-19 00:57:11}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
[01:00:18 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=133, filter=133, success=0, tps=0, ckpt_times=6, lsn_ckpt={6839918517630795777[1592542631, 1], 2020-06-19 00:57:11}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
[01:00:22 EDT 2020/06/19] [INFO] (mongoshake/collector.(*OplogSyncer).startBatcher.func1:266) try to update checkpoint mandatory from 6839918517630795777[1592542631, 1] to 6839919333674582017[1592542821, 1]
[01:00:22 EDT 2020/06/19] [INFO] (mongoshake/collector.(*OplogSyncer).startBatcher.func1:283) waiting last checkpoint[6839919333674582017[1592542821, 1]] updated
[01:00:22 EDT 2020/06/19] [INFO] (mongoshake/collector.(*OplogSyncer).startBatcher.func1:287) last checkpoint[6839919333674582017[1592542821, 1]] updated [false]
[01:00:22 EDT 2020/06/19] [INFO] (mongoshake/collector/ckpt.(*MongoCheckpoint).Insert:134) rc0 Record new checkpoint success [1592542821]
[01:00:22 EDT 2020/06/19] [INFO] (mongoshake/collector.(*OplogSyncer).checkpoint:121) CheckpointOperation write success. updated from 6839918517630795777[1592542631, 1] to 6839919333674582017[1592542821, 1]
[01:00:23 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=135, filter=134, success=0, tps=0, ckpt_times=7, lsn_ckpt={6839919333674582017[1592542821, 1], 2020-06-19 01:00:21}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
[01:00:28 EDT 2020/06/19] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:175) [name=rc0, stage=incr, get=135, filter=135, success=0, tps=0, ckpt_times=7, lsn_ckpt={6839919333674582017[1592542821, 1], 2020-06-19 01:00:21}, lsn_ack={0[0, 0], 1969-12-31 19:00:00}]]
```

配置如下

conf.version = 3
id = mongoshake
master_quorum = false
full_sync.http_port = 9101
incr_sync.http_port = 9100

system_profile_port = 9200
log.dir =

log.file = collector.log
log.flush = false
sync_mode = all
mongo_urls = mongodb://148.70.80.117:29127,mongodb://148.70.80.117:29128,mongodb://148.70.80.117:29129
mongo_cs_url =

mongo_s_url =

tunnel = direct
tunnel.address = mongodb://localhost:29127,mongodb://localhost:29128,mongodb://localhost:29129

tunnel.message = raw

mongo_connect_mode = secondaryPreferred

filter.namespace.black =
filter.namespace.white =

filter.pass.special.db =
filter.ddl_enable = true
checkpoint.storage.url =

checkpoint.storage.collection = ckpt_default

checkpoint.start_position = 1970-01-01T00:00:00Z

transform.namespace =

full_sync.reader.collection_parallel = 6

full_sync.reader.write_document_parallel = 8

full_sync.reader.document_batch_size = 128

full_sync.collection_exist_drop = true

full_sync.create_index = foreground

full_sync.executor.insert_on_dup_update = false

full_sync.executor.filter.orphan_document = false

full_sync.executor.majority_enable = false
>= 4.0
incr_sync.mongo_fetch_method = oplog

incr_sync.oplog.gids =
incr_sync.shard_key = collection

incr_sync.worker = 8

incr_sync.worker.oplog_compressor = none

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert = false

incr_sync.executor.insert_on_dup_update = false

incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false

我的源机器是在国内，目标机器在美国。不知道是否有影响

**Comment by vinllen** [comment]
你没有增量的数据同步，有的都过滤掉了。`get=135, filter=135`
如果你想要重新进行一次全量同步，需要清掉checkpoint重新同步。

**Comment by muyuqingqiu** [comment]
清掉checkpoint是删除目标库里的mongoshake数据库么？
我重启前删除了这个db，但是仍然没有全量同步

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E5%A6%82%E6%9E%9C%E6%88%91%E6%83%B3%E6%B8%85%E6%8E%89%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%95%B0%E6%8D%AE%E9%87%8D%E6%96%B0%E8%BF%9B%E8%A1%8C%E4%B8%80%E6%AC%A1%E5%85%A8%E9%87%8F%E5%A2%9E%E9%87%8F%E5%90%8C%E6%AD%A5%E6%80%8E%E4%B9%88%E5%81%9A

**Comment by muyuqingqiu** [comment]
> https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E5%A6%82%E6%9E%9C%E6%88%91%E6%83%B3%E6%B8%85%E6%8E%89%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%95%B0%E6%8D%AE%E9%87%8D%E6%96%B0%E8%BF%9B%E8%A1%8C%E4%B8%80%E6%AC%A1%E5%85%A8%E9%87%8F%E5%A2%9E%E9%87%8F%E5%90%8C%E6%AD%A5%E6%80%8E%E4%B9%88%E5%81%9A

我看了这个文档，按照要求去删除了相关信息。但是依然无法同步。
我现在有2台机器，A和B，我的mongo_shake安装在B机器上
我这边是想从A机器的数据同步到B机器，但是我现在发现，无论我把mongo_url设置为A机器，tunnel_adress设为B机器，还是反过来，都只会在我的B机器上的mongo里创建mongoshake库。。。
是不是我的设置有问题，新手搞这个，问的有点多，麻烦了。

**Comment by muyuqingqiu** [comment]
我看了这个文档，按照要求去删除了相关信息。但是依然无法同步。
我现在有2台机器，A和B，我的mongo_shake安装在B机器上
我这边是想从A机器的数据同步到B机器，但是我现在发现，无论我把mongo_url设置为A机器，tunnel_adress设为B机器，还是反过来，都只会在我的B机器上的mongo里创建mongoshake库。。。
是不是我的设置有问题，新手搞这个，问的有点多，麻烦了。

**Comment by vinllen** [comment]
对于副本集，checkpoint默认都是写入到源端集群的，除非设置了checkpoint.storage.url。

**Comment by muyuqingqiu** [comment]
我刚刚改了配置文件，依然无法同步。我尝试在B机器添加了一条数据 mymo.my.iinsert({a:1})


这是启动后的log
```
7, 2]]
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/common.NewMongoConn:73) New session to mongodb://148.70.80.107:29128,148.70.80.107:29129 successfully
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/collector/ckpt.(*MongoCheckpoint).Get:100) rc0 Load exist checkpoint. content {"name":"rc0","ckpt":6839987005179297794,"version":1,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/collector.(*OplogSyncer).loadCheckpoint:33) load checkpoint value: {"name":"rc0","ckpt":6839987005179297794,"version":1,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/collector.(*Persister).SetFetchStage:68) persister replset[rc0] update fetch status to: store memory and apply
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/collector/ckpt.(*MongoCheckpoint).Get:100) rc0 Load exist checkpoint. content {"name":"rc0","ckpt":6839987005179297794,"version":1,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/collector/reader.(*OplogReader).SetQueryTimestampOnEmpty:75) set query timestamp: 6839987005179297794[1592558577, 2]
[05:23:16 EDT 2020/06/19] [INFO] (mongoshake/collector/reader.(*OplogReader).fetcher:132) start fetcher with src[mongodb://148.70.80.107:29128,148.70.80.107:29129] replica-name[rc0] query-ts[6839987005179297794[1592558577, 2]]
[05:23:17 EDT 2020/06/19] [INFO] (mongoshake/common.NewMongoConn:73) New session to mongodb://148.70.80.107:29128,148.70.80.107:29129 successfully
[05:23:18 EDT 2020/06/19] [CRIT] (mongoshake/collector.(*Batcher).filter:110) ddl oplog found[{"ts":6839987073898774529,"op":"c","g":"","ns":"mymo.$cmd","o":[{"Name":"drop","Value":"my"}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}] when oplog timestamp[6839987073898774529[1592558593, 1]] less than fullSyncFinishPosition[6839987078193741826[1592558594, 2]]
[05:23:18 EDT 2020/06/19] [CRIT] (mongoshake/collector.(*Batcher).filter:110) ddl oplog found[{"ts":6839987073898774529,"op":"c","g":"","ns":"mymo.$cmd","o":[{"Name":"drop","Value":"my"}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}] when oplog timestamp[6839987073898774529[1592558593, 1]] less than fullSyncFinishPosition[6839987078193741826[1592558594, 2]]
panic: ddl oplog found[{"ts":6839987073898774529,"op":"c","g":"","ns":"mymo.$cmd","o":[{"Name":"drop","Value":"my"}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}] when oplog timestamp[6839987073898774529[1592558593, 1]] less than fullSyncFinishPosition[6839987078193741826[1592558594, 2]]

goroutine 2284 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xd54e8f, 0x51, 0xc420367d00, 0x3, 0x3)
	/root/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector.(*Batcher).filter(0xc42018c0c0, 0xc4201dbb90, 0x3)
	/root/MongoShake/src/mongoshake/collector/batcher.go:110 +0x23f
mongoshake/collector.(*Batcher).BatchMore(0xc42018c0c0, 0xc4228efe88, 0x5a2075, 0xc4228efee0, 0x13e9a20)
	/root/MongoShake/src/mongoshake/collector/batcher.go:234 +0x148
mongoshake/collector.(*OplogSyncer).startBatcher.func1()
	/root/MongoShake/src/mongoshake/collector/syncer.go:222 +0x6b
vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop.func1(0xc420251c20)
	/root/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:19 +0x25
created by vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop
	/root/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:17 +0x3f
root@critical-poke-1:~/MongoShake#
```

看起来程序打算把B的数据同步到A？可是我的目的是把A同步到B。。


我的地址配置如下
mongo_urls = mongodb://148.70.80.109:29128,148.70.80.109:29129  //这是A机器的两个副本地址
tunnel.address = mongodb://localhost:29127,localhost:29128,localhost:29129 //这是B机器的主副地址

checkpoint.storage.url=我没有设置过，就是空的

**Comment by vinllen** [comment]
关于同步链路，请再确认下配置，你说的情况不可能出现。
关于报错：
```
panic: ddl oplog found[{"ts":6839987073898774529,"op":"c","g":"","ns":"mymo.$cmd","o":[{"Name":"drop","Value":"my"}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}] when oplog timestamp[6839987073898774529[1592558593, 1]] less than fullSyncFinishPosition[6839987078193741826[1592558594, 2]]
```
全量同步期间不能有DDL语句，https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99-ddl-oplog-found-when-oplog-timestampxxx-less-than-fullsyncfinishpositionxxx

**Comment by muyuqingqiu** [comment]
[collector.conf](https://github.com/muyuqingqiu/helloWorld/blob/master/collector.conf)

这是我的实际配置，劳烦您帮我看看。我自己对照着文档看了许多次也改了许多次都不成功。。。
麻烦了。

**Comment by vinllen** [comment]
你给的配置文件看不出问题，上面说的报错那个DDL enable你可以关掉。
至于为什么方向反了，我不清楚。
