### ISSUE TITLE
全量传输过程中报错退出

### ISSUE THREAD

**Issue by Simpson877** [alibaba/MongoShake#381]
#报错信息：
[2020/06/30 22:31:34 CST] [CRIT] [docsyncer.(*DBSyncer).collectionSync.func1:419] splitter reader[DocumentReader src[mongodb://root:***@dds-w1231-pub.mongodb.rds.aliyuncs.com:3717,dds-wz2109-pub.mongodb.rds.aliyuncs.com:3717] ns[{texas_xxx_base base_act_string}] query[map[]]] get next document failed: read tcp 192.168.1.222:24612->8.129.150.12:3717: i/o timeout

hypervisor.output信息：
[22:31:34 CST 2020/06/30] [CRIT] (mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1:419) splitter reader[DocumentReader src[mongodb://root:***@dds-wz1231-pub.mongodb.rds.aliyuncs.com:3717,dds-wz2109-pub.mongodb.rds.aliyuncs.com:3717] ns[{texas_xxx_base base_act_string}] query[map[]]] get next document
 failed: read tcp 192.168.1.222:24612->8.129.150.12:3717: i/o timeout
panic: splitter reader[DocumentReader src[mongodb://root:***@dds-wz1231-pub.mongodb.rds.aliyuncs.com:3717,dds-wz2109-pub.mongodb.rds.aliyuncs.com:3717] ns[{texas_xxx_base base_act_string}] query[map[]]] get next document failed: read tcp 192.168.1.222:24612->8.129.150.12:3717: i/o timeout

goroutine 1752 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xcca82b, 0x2, 0xc420721f98, 0x1, 0x1)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc420272c60, 0xc420229290, 0xc421222c00, 0xc42000c560, 0xc4204c8410)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:419 +0xeb
created by mongoshake/collector/docsyncer.(*DBSyncer).collectionSync
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:411 +0x2cc
- child process[10809] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2

#同步信息
源端
base_act_string有2.69亿行数据
mongodb版本：dds-w1231-pub.mongodb.rds.aliyuncs.com mongodb，3.2.13，副本集

目标端
mongodb版本：192.168.1.222，3.4.14，副本集

同步过程是走公网从源端的副本集同步约164G数据到目标端副本集

**Comment by vinllen** [comment]
i/o timeout 这个看起来是网络断开了。你重试几次看看？

**Comment by Simpson877** [comment]
mongo-shake自动重试了
