### ISSUE TITLE
Crash in full sync

### ISSUE THREAD

**Issue by tanisdlj** [alibaba/MongoShake#416]
The database never get's fully sync-ed
Source db: 900Mb
Dest db: 700Mb.

hypervisor.out crashes from time to time with:

```
- execute: "./collector.linux"
panic: send on closed channel

goroutine 101 [running]:
vendor/github.com/vinllen/log4go.(*FileLogWriter).LogWrite(0xc42035e1e0, 0xc420724540)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/filelog.go:45 +0x42
vendor/github.com/vinllen/log4go.Logger.intLogf(0xc420125800, 0x4, 0xcded0b, 0x19, 0xc4202dbd58, 0x2, 0x2)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/log4go.go:223 +0x289
vendor/github.com/vinllen/log4go.Info(0xb9dde0, 0xe12ba0, 0xc4202dbd58, 0x2, 0x2)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:195 +0x1b2
mongoshake/collector/docsyncer.(*DBSyncer).Start.func2()
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:382 +0xa68
vendor/github.com/gugemichael/nimo4go.GoRoutine.func1(0xc4201d8ff0)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:12 +0x25
created by vendor/github.com/gugemichael/nimo4go.GoRoutine
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:11 +0x3f
- child process[20652] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2
```

**Comment by vinllen** [comment]
Is there any more log on collector.log?

**Comment by tanisdlj** [comment]
Nope, it was the typical starting the program, throws this error, closing, restarting, this...

**Comment by vinllen** [comment]
Please attach your `collecgor.conf`, mongoshake version, source mongodb, target mongodb version and type(sharding or replica)

**Comment by tanisdlj** [comment]
Mongoshake: v2.4.9_3
Source mongo: v4.0.10
Target mongo: v4.2.8
Mongo type: Replica set


collector.conf:
```
conf.version = 5
id = mongoshake
master_quorum = false

full_sync.http_port = 9101
incr_sync.http_port = 9100
system_profile_port = 9200

log.level = info

log.dir = 
log.file = collector.log

log.flush = false

sync_mode = full

mongo_urls = mongodb://{{ MONGO_LOGIN_USER }}:{{ MONGO_LOGIN_PASSWORD }}@{{ host }},{{ MONGO_LOGIN_USER2 }}:{{ MONGO_LOGIN_PASSWORD2 }}@{{ host2 }}

mongo_cs_url =
mongo_s_url =

tunnel = direct
tunnel.address = mongodb://{{ MONGO_LOGIN_USER }}:{{ MONGO_LOGIN_PASSWORD }}@{{ target_host }}
tunnel.message = raw

mongo_connect_mode = secondaryPreferred

filter.namespace.black =
filter.namespace.white = 
filter.pass.special.db =

filter.ddl_enable = false

checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.start_position = 1970-01-01T00:00:00Z

transform.namespace =

# --------------------------- full sync configuration ---------------------------
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.read_document_count = 0
full_sync.collection_exist_drop = true
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false

# --------------------------- incrmental sync configuration ---------------------------
incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.worker = 8
incr_sync.worker.oplog_compressor = none
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

# --- direct tunnel only begin ---
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false

# --- direct tunnel only end ---
incr_sync.change_stream.watch_full_document = false

```

**Comment by vinllen** [comment]
It should have more log on `collector.log` and `hypervisor.log`, please send these two logs to my mail(cvinllen@gmail.com) at your convenience.

**Comment by lizer2014** [comment]
你好， 我也遇到了一样的问题，分片集群间全量同步过程中，运行一段时间后，会有如下超时错误，然后进程重启重新同步， 请问解决了吗？

Mongoshake: v2.6.5
Source mongo: v4.0.24
Target mongo: v4.0.24
Mongo type: 源端和目标端 都是 shard （3分片）

error:
```bash
- execute: "./collector.linux"
[13:10:19 CST 2022/02/11] [CRIT] (github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start:171) DocExecutor[427] collectionExecutor[{xx-ns xx-collec_test}] sync failed: bulk run message[[{_id ObjectIdHex("5e203970c143ae104c1ed098")} xxxx ]], failed[read tcp {mongoshake_ip}:38656->{dest_mongo_ip}:20400: i/o timeout], index[0] dup[false]

goroutine 3872 [running]:
github.com/vinllen/log4go.Crashf(0xec4b1f, 0x12, 0xc001ae7f98, 0x2, 0x2)
    /Users/zhangst/language/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:46 +0xe5
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc002d54120)
    /Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:171 +0x174
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
    /Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
- child process[29478] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2
```

collector.conf:
```bash
conf.version = 10

id = mongoshake

master_quorum = false

full_sync.http_port = 6101
incr_sync.http_port = 6100
system_profile_port = 6200

log.level = debug
log.dir =
log.file = collector.log
log.flush = true

sync_mode = all

mongo_urls = mongodb://{{user}}:{{password}}@{xxx}:9100,{{xxxx}}:9100,{xxx}:9100;mongodb://{{user}}:{{password}}@{xxx}:9101,{{xxxx}}:9101,{xxx}:9101;mongodb://{{user}}:{{password}}@{xxx}:9102,{{xxxx}}:9102,{xxx}:9102
mongo_cs_url = mongodb://{{user}}:{{password}}@{xxx}:8091,{{xxxx}}:8091,{xxx}:8091
mongo_s_url = mongodb://{{user}}:{{password}}@{xxx}:20100,{{xxxx}}:20100,{xxx}:20100
mongo_ssl_root_ca_file =

tunnel = direct
tunnel.address = mongodb://{{user}}:{{password}}@{xxx}:20400,{{xxxx}}:20400,{xxx}:20400
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =

mongo_connect_mode = secondaryPreferred

filter.namespace.black =
filter.namespace.white =
filter.pass.special.db =
filter.ddl_enable = true
filter.oplog.gids = false

checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file =
checkpoint.start_position = 1970-01-01T00:00:00Z

transform.namespace =

full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = shard_key

full_sync.collection_exist_drop = true

full_sync.create_index = background

full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false

incr_sync.mongo_fetch_method = change_stream

incr_sync.change_stream.watch_full_document = false

incr_sync.oplog.gids =

incr_sync.shard_key = auto
incr_sync.shard_by_object_id_whitelist =

incr_sync.worker = 8

incr_sync.tunnel.write_thread = 8

incr_sync.target_delay = 0

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none

incr_sync.executor.majority_enable = false

special.source.db.flag =
```
