### ISSUE TITLE
请教：副本集单向同步报如下错误

### ISSUE THREAD

**Issue by dbing** [alibaba/MongoShake#443]
version: mongo-shake-v2.4.12

conf 配置：
sync_mode = all
tunnel = direct

执行命令：/collector.linux -conf=collector-jp-to-sh.conf -verbose

错误日志：
[2020/09/10 11:12:49 CST] [CRIT] splitter reader[DocumentReader src[mongodb://root:***@host] ns[{sushi_test demo}] query[map[]]] get next document failed: (CursorNotFound) cursor id 107226531868 not found

输出此错误后进程就崩溃了，请问是什么原因引起的呢？

**Comment by dbing** [comment]
完整的错误日志：

```
[2020/09/10 17:32:44 CST] [CRIT] splitter reader[DocumentReader src[mongodb://root:***@host:port/admin?replicaSet=mgset-3504xxx] ns[{sushi_master mansion_master}] query[map[]]] get next document failed: (CursorNotFound) cursor id 103316212717 not found
[17:32:44 CST 2020/09/10] [CRIT] (mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1:422) splitter reader[DocumentReader src[mongodb://root:***@host:port/admin?replicaSet=mgset-3504xxx] ns[{sushi_master mansion_master}] query[map[]]] get next document failed: (CursorNotFound) cursor id 103316212717 not found
panic: splitter reader[DocumentReader src[mongodb://root:***@host:port/admin?replicaSet=mgset-3504xxx] ns[{sushi_master mansion_master}] query[map[]]] get next document failed: (CursorNotFound) cursor id 103316212717 not found

goroutine 9313 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xcd49ec, 0x2, 0xc4213cbf98, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc42051c6c0, 0xc4200b9d60, 0xc42110cc00, 0xc4203eff60, 0xc420a0cf70)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:422 +0xeb
created by mongoshake/collector/docsyncer.(*DBSyncer).collectionSync
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:414 +0x2cc
```

**Comment by vinllen** [comment]
日志还有吗？这个报错之前对应reader是不是block了较长时间，看起来是源端mongodb给释放了这个cursor导致find get more拉取失败了

**Comment by dbing** [comment]
以下是日志：
```
2020/09/11 14:49:38 CST] [INFO] splitter reader finishes: DocumentReader src[mongodb://root:***@host] ns[{sushi_user users}] query[map[]]
[2020/09/11 14:49:38 CST] [INFO] Close session with mongodb://root:***@host
[2020/09/11 14:49:38 CST] [INFO] Close session with mongodb://root:***@host
[2020/09/11 14:49:38 CST] [INFO] DBSyncer id[0] source[mongodb://root:***@host] target[mongodb://root:***@host] startTime[2020-09-11 14:27:21.258586412 +0800 CST m=+8.946843076] collExecutor-2 sync ns {sushi_user users} to {sushi_user users} successful. db syncer-0 progress 91%
[2020/09/11 14:49:39 CST] [INFO] New session to mongodb://root:***@host successfully
[2020/09/11 14:49:41 CST] [INFO] [name=mgset-350414029, stage=full, get=116458, tps=0]
[2020/09/11 14:49:42 CST] [INFO] splitter reader finishes: DocumentReader src[mongodb://root:***@host] ns[{sushi_user video_trans_notify}] query[map[]]
[2020/09/11 14:49:42 CST] [INFO] Close session with mongodb://root:***@host
[2020/09/11 14:49:42 CST] [INFO] Close session with mongodb://root:***@host
[2020/09/11 14:49:42 CST] [INFO] DBSyncer id[0] source[mongodb://root:***@host] target[mongodb://root:***@host] startTime[2020-09-11 14:27:21.258586412 +0800 CST m=+8.946843076] collExecutor-5 sync ns {sushi_user video_trans_notify} to {sushi_user video_trans_notify} successful. db syncer-0 progress 92%
[2020/09/11 14:49:46 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:49:51 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:49:56 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:01 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:06 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:11 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:16 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:21 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:26 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:31 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:36 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:41 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:46 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:51 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:50:56 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:51:01 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:51:06 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:51:11 CST] [INFO] [name=mgset-350414029, stage=full, get=116569, tps=0]
[2020/09/11 14:51:12 CST] [CRIT] splitter reader[DocumentReader src[mongodb://root:***@host] ns[{sushi_user news_pages}] query[map[]]] get next document failed: (CursorNotFound) cursor id 68896444083 not found
```

**Comment by dbing** [comment]
将 mogoshake 架在国内服务器，启动日本到中国同步进程时，多次触发此问题，我们推测可能是网络环境问题导致查询不到某个数据导致，后面尝试了将 mogoshake 架在日本服务器，然后配置双向同步，便了没了此问题的发生，目前已在生产上使用上 mogoshake 的双向同步，感谢~

**Comment by zj452008181** [comment]
> 将mogoshake架在国内服务器上，启动日本到中国同步进程时，多次触发此问题，我们据称可能是网络环境问题导致查询不到某数据导致，后面尝试了将mogoshake架在日本服务器上，然后配置双向同步，便了没了此问题的发生，目前已在生产上使用上mogoshake的双向同步，感谢〜

请问下你们的双向同步，MongoDB是用的阿里云上的还是社区版的

**Comment by dbing** [comment]
> > 将mogoshake架在国内服务器上，启动日本到中国同步进程时，多次触发此问题，我们据称可能是网络环境问题导致查询不到某数据导致，后面尝试了将mogoshake架在日本服务器上，然后配置双向同步，便了没了此问题的发生，目前已在生产上使用上mogoshake的双向同步，感谢〜
> 
> 请问下你们的双向同步，MongoDB是用的阿里云上的还是社区版的

阿里云的，云数据库MongoDB版，需要联系他们技术开通一个参数。

**Comment by dbing** [comment]
> > 将mogoshake架在国内服务器上，启动日本到中国同步进程时，多次触发此问题，我们据称可能是网络环境问题导致查询不到某数据导致，后面尝试了将mogoshake架在日本服务器上，然后配置双向同步，便了没了此问题的发生，目前已在生产上使用上mogoshake的双向同步，感谢〜
> 
> 请问下你们的双向同步，MongoDB是用的阿里云上的还是社区版的

阿里云的，云数据库MongoDB版，需要联系他们技术开通一个参数，mongoshake 上有说明。
