### ISSUE TITLE
mongoshake分片表增量同步到kafka异常

### ISSUE THREAD

**Issue by tmm01** [alibaba/MongoShake#486]
### 问题描述
表未分片，增量同步正常。但增加分片表后，增量同步报异常
### 版本说明
源端为mongos集群，4分片，版本3.6.6
mongo-shake-v2.4.6
目标端kafka：kafka_2.11-1.0.0.jar 
### kafka配置
已经修改topci大小为16M
/opt/kafka/bin/kafka-topics.sh --zookeeper xxxx:2181,xxxx:2181,xxxx:2181 --topic mongo_oplog --alter --config max.message.bytes=16777216
### mongoshake配置
conf.version = 4
id = mongo3
master_quorum = true
full_sync.http_port = 9301
incr_sync.http_port = 9302
system_profile_port = 9303
log.level = info
log.dir = /var/log/mongo_shake/
log.file = mongo3.log
log.flush = false
sync_mode = incr
mongo_urls = mongodb://root:xxxx@xxxx:10000,xxxx:10000,xxxx:10000;mongodb://root:xxxx@xxxx:11000,xxxx:11000,xxxx:11000;mongodb://root:xxxx@xxxx:12000,xxxx:12000,xxxx:12000;mongodb://root:xxxx@xxxx:13000,xxxx:13000,xxxx:13000

mongo_cs_url = mongodb://root:xxxx@xxxx:40000,xxxx:40000,xxxx:40000
mongo_s_url = mongodb://root:xxxx@xxxx:50000,xxxx:50000,xxxx:50000
tunnel = kafka
tunnel.address = mongo_oplog@xxxx:9092,xxxx:9092,xxxx:9092
tunnel.message = json
mongo_connect_mode = secondaryPreferred
filter.namespace.black =
filter.namespace.white = db1.table1;db2.table2
filter.pass.special.db =
filter.ddl_enable = false
checkpoint.storage.url =
checkpoint.storage.db =
checkpoint.storage.collection = ckpt_001
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.collection_exist_drop = true
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false
incr_sync.mongo_fetch_method = oplog
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.worker = 8
incr_sync.worker.oplog_compressor = none
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false
### mongoshake启动后，报如下日志
[2020/11/20 20:21:43 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000 successfully
[2020/11/20 20:21:48 CST] [INFO] [quorum.BecomeMaster:144] Expired master found. compete to become master
[2020/11/20 20:21:59 CST] [INFO] [quorum.masterChanged:42] become the master and notify waiter
[2020/11/20 20:21:59 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000 successfully
[2020/11/20 20:21:59 CST] [INFO] [common.(*MongoConn).Close:78] Close session with mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000
[2020/11/20 20:21:59 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000 successfully
[2020/11/20 20:21:59 CST] [INFO] [common.(*MongoConn).HasUniqueIndex:152] Found unique index proof_book_count_idx on xh_QuestionPublish.proofBookCount in auto shard mode
[2020/11/20 20:21:59 CST] [INFO] [common.(*MongoConn).Close:78] Close session with mongodb://root:***@xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000
[2020/11/20 20:21:59 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000 successfully
[2020/11/20 20:21:59 CST] [INFO] [common.(*MongoConn).Close:78] Close session with mongodb://root:***@xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000
[2020/11/20 20:21:59 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0 successfully
[2020/11/20 20:21:59 CST] [INFO] [common.(*MongoConn).Close:78] Close session with mongodb://root:***@xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0
[2020/11/20 20:21:59 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000 successfully
[2020/11/20 20:21:59 CST] [INFO] [common.(*MongoConn).Close:78] Close session with mongodb://root:***@xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000
[2020/11/20 20:21:59 CST] [INFO] [coordinator.(*ReplicationCoordinator).Run:45] Collector startup. shard_by[collection] gids[[]]
[2020/11/20 20:21:59 CST] [INFO] [coordinator.(*ReplicationCoordinator).Run:50] Collector configuration {"ConfVersion":4,"Id":"mongo3","MasterQuorum":true,"FullSyncHTTPListenPort":9301,"IncrSyncHTTPListenPort":9302,"SystemProfilePort":9303,"LogLevel":"info","LogDirectory":"/var/log/mongo_shake/","LogFileName":"mongo3.log","LogFlush":false,"SyncMode":"incr","MongoUrls":["mongodb://root:***@xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000","mongodb://root:***@xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000","mongodb://root:***@xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0","mongodb://root:***@xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000"],"MongoCsUrl":"mongodb://root:***@xxx.xx.xx.xxx:40000,xxx.xx.xx.xxx:40000,xxx.xx.xx.xxx:40000","MongoSUrl":"mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000","MongoConnectMode":"secondaryPreferred","Tunnel":"kafka","TunnelAddress":["mongo_oplog@172.16.30.51:9092,172.16.30.52:9092,172.16.30.53:9092"],"TunnelMessage":"json","FilterNamespaceBlack":[],"FilterNamespaceWhite":["xh_cloudwork_parts.work","xh_cloudwork_parts.studentWork"],"FilterPassSpecialDb":[],"FilterDDLEnable":false,"CheckpointStorageUrl":"mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000","CheckpointStorageDb":"mongoshake","CheckpointStorageCollection":"ckpt_001","CheckpointStartPosition":1,"TransformNamespace":[],"FullSyncReaderCollectionParallel":6,"FullSyncReaderWriteDocumentParallel":8,"FullSyncReaderReadDocumentCount":0,"FullSyncReaderDocumentBatchSize":128,"FullSyncCollectionDrop":true,"FullSyncCreateIndex":"none","FullSyncReaderOplogStoreDisk":false,"FullSyncReaderOplogStoreDiskMaxSize":256000,"FullSyncExecutorInsertOnDupUpdate":false,"FullSyncExecutorFilterOrphanDocument":false,"FullSyncExecutorMajorityEnable":false,"IncrSyncMongoFetchMethod":"oplog","IncrSyncOplogGIDS":[],"IncrSyncShardKey":"collection","IncrSyncWorker":4,"IncrSyncWorkerOplogCompressor":"none","IncrSyncTargetDelay":0,"IncrSyncWorkerBatchQueueSize":64,"IncrSyncAdaptiveBatchingMaxSize":1024,"IncrSyncFetcherBufferCapacity":256,"IncrSyncExecutorUpsert":false,"IncrSyncExecutorInsertOnDupUpdate":false,"IncrSyncConflictWriteTo":"none","IncrSyncExecutorMajorityEnable":false,"CheckpointStorage":"database","CheckpointInterval":5000,"FullSyncExecutorDebug":false,"IncrSyncDBRef":false,"IncrSyncExecutor":1,"IncrSyncExecutorDebug":false,"IncrSyncReaderDebug":"","IncrSyncCollisionEnable":false,"IncrSyncReaderBufferTime":1,"Version":"improve-2.4.6,69e0712888410509a2b1ce8721534658826b6aeb,release,go1.10.3,2020-06-17_11:52:11","IncrSyncTunnel":"","IncrSyncTunnelAddress":null,"IncrSyncTunnelMessage":"","HTTPListenPort":0,"SystemProfile":0}
[2020/11/20 20:21:59 CST] [INFO] [coordinator.(*ReplicationCoordinator).Run:68] start running with mode[incr], fullBeginTs[0[0, 0]]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*Worker).StartWorker:127] Collector-worker-0 start working with jobs batch queue. buffer capacity 64
[2020/11/20 20:21:59 CST] [INFO] [collector.(*Worker).StartWorker:127] Collector-worker-1 start working with jobs batch queue. buffer capacity 64
[2020/11/20 20:21:59 CST] [INFO] [collector.(*Worker).StartWorker:127] Collector-worker-2 start working with jobs batch queue. buffer capacity 64
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).Start:178] Poll oplog syncer start. ckpt_interval[5000ms], gid[[]], shard_key[collection]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).Start:178] Poll oplog syncer start. ckpt_interval[5000ms], gid[[]], shard_key[collection]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).newCheckpointManager:19] Oplog sync[shard1] create checkpoint manager with url[mongodb://root:xhmondata%40321@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000] table[mongoshake.ckpt_001] start-position[1[0, 1]]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).newCheckpointManager:19] Oplog sync[shard3] create checkpoint manager with url[mongodb://root:xhmondata%40321@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000] table[mongoshake.ckpt_001] start-position[1[0, 1]]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).Start:178] Poll oplog syncer start. ckpt_interval[5000ms], gid[[]], shard_key[collection]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).Start:178] Poll oplog syncer start. ckpt_interval[5000ms], gid[[]], shard_key[collection]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).newCheckpointManager:19] Oplog sync[shard4] create checkpoint manager with url[mongodb://root:xhmondata%40321@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000] table[mongoshake.ckpt_001] start-position[1[0, 1]]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*OplogSyncer).newCheckpointManager:19] Oplog sync[shard2] create checkpoint manager with url[mongodb://root:xhmondata%40321@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000] table[mongoshake.ckpt_001] start-position[1[0, 1]]
[2020/11/20 20:21:59 CST] [INFO] [collector.(*Worker).StartWorker:127] Collector-worker-3 start working with jobs batch queue. buffer capacity 64
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000 successfully
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000 successfully
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000 successfully
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard1 Regenerate checkpoint but won't persist. content: {"name":"shard1","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*OplogSyncer).loadCheckpoint:33] load checkpoint value: {"name":"shard1","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*Persister).SetFetchStage:68] persister replset[shard1] update fetch status to: store memory and apply
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000,xxx.xx.xx.xxx:50000 successfully
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard4 Regenerate checkpoint but won't persist. content: {"name":"shard4","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*OplogSyncer).loadCheckpoint:33] load checkpoint value: {"name":"shard4","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*Persister).SetFetchStage:68] persister replset[shard4] update fetch status to: store memory and apply
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard3 Regenerate checkpoint but won't persist. content: {"name":"shard3","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*OplogSyncer).loadCheckpoint:33] load checkpoint value: {"name":"shard3","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*Persister).SetFetchStage:68] persister replset[shard3] update fetch status to: store memory and apply
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard1 Regenerate checkpoint but won't persist. content: {"name":"shard1","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).SetQueryTimestampOnEmpty:75] set query timestamp: 1[0, 1]
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).fetcher:132] start fetcher with src[mongodb://root:***@xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000] replica-name[shard1] query-ts[1[0, 1]]
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard3 Regenerate checkpoint but won't persist. content: {"name":"shard3","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).SetQueryTimestampOnEmpty:75] set query timestamp: 1[0, 1]
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard4 Regenerate checkpoint but won't persist. content: {"name":"shard4","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).SetQueryTimestampOnEmpty:75] set query timestamp: 1[0, 1]
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).fetcher:132] start fetcher with src[mongodb://root:***@xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0] replica-name[shard3] query-ts[1[0, 1]]
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).fetcher:132] start fetcher with src[mongodb://root:***@xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000] replica-name[shard4] query-ts[1[0, 1]]
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard2 Regenerate checkpoint but won't persist. content: {"name":"shard2","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*OplogSyncer).loadCheckpoint:33] load checkpoint value: {"name":"shard2","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [collector.(*Persister).SetFetchStage:68] persister replset[shard2] update fetch status to: store memory and apply
[2020/11/20 20:22:00 CST] [INFO] [ckpt.(*MongoCheckpoint).Get:111] shard2 Regenerate checkpoint but won't persist. content: {"name":"shard2","ckpt":1,"version":2,"fetch_method":"","oplog_disk_queue":"","oplog_disk_queue_apply_finish_ts":1}
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).SetQueryTimestampOnEmpty:75] set query timestamp: 1[0, 1]
[2020/11/20 20:22:00 CST] [INFO] [reader.(*OplogReader).fetcher:132] start fetcher with src[mongodb://root:***@xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000] replica-name[shard2] query-ts[1[0, 1]]
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000,xxx.xx.xx.xxx:10000 successfully
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000,xxx.xx.xx.xxx:13000 successfully
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0,xxx.xx.xx.xxx:1xxx0 successfully
[2020/11/20 20:22:00 CST] [WARN] [reader.(*OplogReader).EnsureNetwork:206] oplog_reader current starting point[1[0, 1]] is smaller than the oldest timestamp[6888645449884893338[1603887754, 154]]!
[2020/11/20 20:22:00 CST] [INFO] [common.NewMongoConn:73] New session to mongodb://root:***@xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000,xxx.xx.xx.xxx:11000 successfully
[2020/11/20 20:22:00 CST] [WARN] [reader.(*OplogReader).EnsureNetwork:206] oplog_reader current starting point[1[0, 1]] is smaller than the oldest timestamp[6867889818563510469[1599055207, 197]]!
[2020/11/20 20:22:00 CST] [WARN] [reader.(*OplogReader).EnsureNetwork:206] oplog_reader current starting point[1[0, 1]] is smaller than the oldest timestamp[6894103640353538528[1605158588, 480]]!
[20:22:00 CST 2020/11/20] [CRIT] (mongoshake/collector.(*Batcher).filter:119) move chunk oplog found[{"ts":6867889818563510469,"op":"i","g":"","ns":"xh_cloudwork_parts.studentWork","o":[xxxx],"o2":null,"uk":null,"lsid":null,"fromMigrate":true}]
[2020/11/20 20:22:00 CST] [CRIT] [collector.(*Batcher).filter:119] move chunk oplog found[{"ts":6867889818563510469,"op":"i","g":"","ns":"xh_cloudwork_parts.studentWork","o":[xxxx],"o2":null,"uk":null,"lsid":null,"fromMigrate":true}]
[2020/11/20 20:22:00 CST] [WARN] [reader.(*OplogReader).EnsureNetwork:206] oplog_reader current starting point[1[0, 1]] is smaller than the oldest timestamp[6894238081419837445[1605189890, 5]]!
panic: move chunk oplog found[{"ts":6867889818563510469,"op":"i","g":"","ns":"xh_cloudwork_parts.studentWork","o":[xxxx],"o2":null,"uk":null,"lsid":null,"fromMigrate":true}]

goroutine 402 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xcdc601, 0x1a, 0xc42334dd08, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector.(*Batcher).filter(0xc42048a0e0, 0xc4xxxa2090, 0x100)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/batcher.go:119 +0x309
mongoshake/collector.(*Batcher).BatchMore(0xc42048a0e0, 0xa9, 0xa9, 0xe0f6f0, 0x1000000cd)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/batcher.go:294 +0x12d
mongoshake/collector.(*OplogSyncer).startBatcher.func1()
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/syncer.go:xxx +0x6b
vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop.func1(0xc4204d0090)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:19 +0x25
created by vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop
        `/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:17` `+0x3f`

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99move-chunk-oplog-found
