### ISSUE TITLE
MongoShake-v2.4.15，数据源为分片集群，输出是Kafka，运行一段时间后，任务自动推出。

### ISSUE THREAD

**Issue by bishuilantian1** [alibaba/MongoShake#511]
goroutine 693 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xce77e6, 0x1a, 0xc4b7577c20, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector.(*Batcher).filter(0xc420354380, 0xc43c4f15e0, 0xc42d4a1701)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/batcher.go:128 +0x364
mongoshake/collector.(*Batcher).BatchMore(0xc420354380, 0x5fd8db5a00000000, 0x5fd8db5a00000055, 0x0, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/batcher.go:327 +0x143
mongoshake/collector.(*OplogSyncer).startBatcher.func1()
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/syncer.go:244 +0x94
vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop.func1(0xc420288ff0)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:19 +0x25
created by vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:17 +0x3f
- child process[11845] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2

**Comment by bishuilantian1** [comment]
重启报错日志：
goroutine 715 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xce77e6, 0x1a, 0xc4203b5c20, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector.(*Batcher).filter(0xc4202120e0, 0xc44e91d4a0, 0xc44edb7901)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/batcher.go:128 +0x364
mongoshake/collector.(*Batcher).BatchMore(0xc4202120e0, 0x5fd8db9c00000000, 0x5fd8db9c0000000d, 0x0, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/batcher.go:327 +0x143
mongoshake/collector.(*OplogSyncer).startBatcher.func1()
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/syncer.go:244 +0x94
vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop.func1(0xc420261bc0)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:19 +0x25
created by vendor/github.com/gugemichael/nimo4go.GoRoutineInLoop
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/gugemichael/nimo4go/runtime.go:17 +0x3f
- child process[12177] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2

- process: "./collector.linux" exit, restart it
- execute: "./collector.linux"
- execute: "./collector.linux"
2020/12/16 17:39:26 listen tcp :9201: bind: address already in use
[17:39:26 CST 2020/12/16] [CRIT] (mongoshake/common.WritePidById:210) Process write pid and lock file failed : Locked by other process
- child process[12200] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 0

- process: "./collector.linux" exit, restart it
- execute: "./collector.linux"
2020/12/16 17:39:36 listen tcp :9201: bind: address already in use
[17:39:36 CST 2020/12/16] [CRIT] (mongoshake/common.WritePidById:210) Process write pid and lock file failed : Locked by other process
- child process[12209] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 0

- process: "./collector.linux" exit, restart it

**Comment by bishuilantian1** [comment]
问题已解决，是mongos开启了balancer，发生move chunk导致同步退出了，对于源端是sharding的情况，如果用oplog格式拉取，需要关闭balancer，如果不能关闭balancer，需要使用2.4版本以上的，使用change stream同步。
