### ISSUE TITLE
全量同步报错 panic: send on closed channel

### ISSUE THREAD

**Issue by Jannchie** [alibaba/MongoShake#517]
```
panic: send on closed channel

goroutine 353 [running]:
vendor/github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc4200ae760, 0xc42062d400)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/termlog.go:41 +0x43
vendor/github.com/vinllen/log4go.Logger.intLogf(0xc42009d800, 0x7, 0xcd69f4, 0x2, 0xc420299f98, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/log4go.go:223 +0x289
vendor/github.com/vinllen/log4go.Crashf(0xcd69f4, 0x2, 0xc420299f98, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:44 +0x6c
mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc4202d0ea0, 0xc4202c6280, 0xc4200eb700, 0xc42042ce20, 0xc42046fe80)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:422 +0xeb
created by mongoshake/collector/docsyncer.(*DBSyncer).collectionSync
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:414 +0x2cc
```

**Comment by Jannchie** [comment]
配置项没有其他的修改

日志：

```
[2020/12/22 05:17:34 UTC] [WARN] 
______________________________
\                             \           _         ______ |
 \                             \        /   \___-=O'/|O'/__|
  \  MongoShake, Here we go !!  \_______\          / | /    )
  /                             /        '/-==__ _/__|/__=-|  -GM
 /        Alibaba Cloud        /         *             \ | |
/                             /                        (o)
------------------------------

if you have any problem, please visit https://github.com/alibaba/MongoShake/wiki/FAQ

[2020/12/22 05:17:35 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:17:36 UTC] [INFO] Close session with mongodb://127.0.0.1:2000
[2020/12/22 05:17:37 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:17:38 UTC] [INFO] Close session with mongodb://127.0.0.1:2000
[2020/12/22 05:17:38 UTC] [INFO] Collector startup. shard_by[collection] gids[[]]
[2020/12/22 05:17:38 UTC] [INFO] Collector configuration {"ConfVersion":7,"Id":"mongoshake","MasterQuorum":false,"FullSyncHTTPListenPort":9101,"IncrSyncHTTPListenPort":9100,"SystemProfilePort":9200,"LogLevel":"info","LogDirectory":"","LogFileName":"collector.log","LogFlush":false,"SyncMode":"full","MongoUrls":["mongodb://127.0.0.1:2000"],"MongoCsUrl":"","MongoSUrl":"","MongoConnectMode":"secondaryPreferred","Tunnel":"direct","TunnelAddress":["mongodb://127.0.0.1:27017"],"TunnelMessage":"raw","FilterNamespaceBlack":[],"FilterNamespaceWhite":[],"FilterPassSpecialDb":[],"FilterDDLEnable":false,"FilterOplogGids":false,"CheckpointStorageUrl":"mongodb://127.0.0.1:2000","CheckpointStorageDb":"mongoshake","CheckpointStorageCollection":"ckpt_default","CheckpointStartPosition":1,"TransformNamespace":[],"FullSyncReaderCollectionParallel":6,"FullSyncReaderWriteDocumentParallel":8,"FullSyncReaderReadDocumentCount":0,"FullSyncReaderDocumentBatchSize":128,"FullSyncCollectionDrop":true,"FullSyncCreateIndex":"none","FullSyncReaderOplogStoreDisk":false,"FullSyncReaderOplogStoreDiskMaxSize":256000,"FullSyncExecutorInsertOnDupUpdate":false,"FullSyncExecutorFilterOrphanDocument":false,"FullSyncExecutorMajorityEnable":false,"IncrSyncMongoFetchMethod":"oplog","IncrSyncChangeStreamWatchFullDocument":false,"IncrSyncOplogGIDS":[],"IncrSyncShardKey":"collection","IncrSyncShardByObjectIdWhiteList":[],"IncrSyncWorker":8,"IncrSyncTargetDelay":0,"IncrSyncWorkerOplogCompressor":"none","IncrSyncWorkerBatchQueueSize":64,"IncrSyncAdaptiveBatchingMaxSize":1024,"IncrSyncFetcherBufferCapacity":256,"IncrSyncExecutorUpsert":false,"IncrSyncExecutorInsertOnDupUpdate":false,"IncrSyncConflictWriteTo":"none","IncrSyncExecutorMajorityEnable":false,"CheckpointStorage":"database","CheckpointInterval":5000,"FullSyncExecutorDebug":false,"IncrSyncDBRef":false,"IncrSyncExecutor":1,"IncrSyncExecutorDebug":false,"IncrSyncReaderDebug":"","IncrSyncCollisionEnable":false,"IncrSyncReaderBufferTime":1,"SourceDBVersion":"4.4.1","TargetDBVersion":"4.4.2","Version":"improve-2.4.17,1bd74130fcb4214b6d68fafa758d7df470045494,release,go1.10.3,2020-12-18_16:28:46","IncrSyncTunnel":"","IncrSyncTunnelAddress":null,"IncrSyncTunnelMessage":"","HTTPListenPort":0,"SystemProfile":0}
[2020/12/22 05:17:38 UTC] [INFO] start running with mode[full], fullBeginTs[0[0, 0]]
[2020/12/22 05:17:38 UTC] [INFO] source is replica or mongos, no need to fetching chunk map
[2020/12/22 05:17:41 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:17:55 UTC] [INFO] Close session with mongodb://127.0.0.1:2000
[2020/12/22 05:17:55 UTC] [INFO] all namespace: map[  .................................  ]
[2020/12/22 05:17:55 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:17:55 UTC] [INFO] replication from [replica] to [replica]
[2020/12/22 05:17:55 UTC] [INFO] document syncer-0 do replication for url=mongodb://127.0.0.1:2000
[2020/12/22 05:17:57 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:00 UTC] [INFO] [name=M0, stage=full, get=0, write_success=0, tps=0]
[2020/12/22 05:18:05 UTC] [INFO] [name=M0, stage=full, get=0, write_success=0, tps=0]
[2020/12/22 05:18:06 UTC] [INFO] Close session with mongodb://127.0.0.1:2000
[2020/12/22 05:18:06 UTC] [INFO] DBSyncer id[0] source[mongodb://127.0.0.1:2000] target[mongodb://127.0.0.1:27017] startTime[2020-12-22 05:17:55.479166187 +0000 UTC m=+24.992782807] collExecutor-5 sync ns .....
[2020/12/22 05:18:06 UTC] [INFO] DBSyncer id[0] source[mongodb://127.0.0.1:2000] target[mongodb://127.0.0.1:27017] startTime[2020-12-22 05:17:55.479166187 +0000 UTC m=+24.992782807] collExecutor-0 sync ns .....
[2020/12/22 05:18:06 UTC] [INFO] DBSyncer id[0] source[mongodb://127.0.0.1:2000] target[mongodb://127.0.0.1:27017] startTime[2020-12-22 05:17:55.479166187 +0000 UTC m=+24.992782807] collExecutor-2 sync ns .....
[2020/12/22 05:18:06 UTC] [INFO] DBSyncer id[0] source[mongodb://127.0.0.1:2000] target[mongodb://127.0.0.1:27017] startTime[2020-12-22 05:17:55.479166187 +0000 UTC m=+24.992782807] collExecutor-1 sync ns .....
[2020/12/22 05:18:06 UTC] [INFO] DBSyncer id[0] source[mongodb://127.0.0.1:2000] target[mongodb://127.0.0.1:27017] startTime[2020-12-22 05:17:55.479166187 +0000 UTC m=+24.992782807] collExecutor-4 sync ns .....
[2020/12/22 05:18:06 UTC] [INFO] DBSyncer id[0] source[mongodb://127.0.0.1:2000] target[mongodb://127.0.0.1:27017] startTime[2020-12-22 05:17:55.479166187 +0000 UTC m=+24.992782807] collExecutor-3 sync ns .....
[2020/12/22 05:18:06 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:18:06 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:18:06 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:18:06 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:18:06 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:18:06 UTC] [INFO] New session to mongodb://127.0.0.1:27017 successfully
[2020/12/22 05:18:08 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:08 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:08 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:08 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:08 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:08 UTC] [INFO] New session to mongodb://127.0.0.1:2000 successfully
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... [0] pieceSize[0] pieceNumber[1]] disable split or no need
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... eSize[0] pieceNumber[1]] disable split or no need
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... nt[1630846] pieceSize[0] pieceNumber[1]] disable split or no need
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... [0] pieceSize[0] pieceNumber[1]] exits
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... eSize[0] pieceNumber[1]] exits
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... nt[1630846] pieceSize[0] pieceNumber[1]] exits
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... pieceSize[0] pieceNumber[1]] disable split or no need
[2020/12/22 05:18:08 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... pieceSize[0] pieceNumber[1]] exits
[2020/12/22 05:18:09 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... ] pieceSize[0] pieceNumber[1]] disable split or no need
[2020/12/22 05:18:09 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... ] pieceSize[0] pieceNumber[1]] exits
[2020/12/22 05:18:09 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... unt[255564] pieceSize[0] pieceNumber[1]] disable split or no need
[2020/12/22 05:18:09 UTC] [INFO] splitter[DocumentSplitter src[mongodb://127.0.0.1:2000] ..... unt[255564] pieceSize[0] pieceNumber[1]] exits
[2020/12/22 05:18:10 UTC] [INFO] [name=M0, stage=full, get=0, write_success=0, tps=0]
[2020/12/22 05:18:15 UTC] [INFO] [name=M0, stage=full, get=0, write_success=0, tps=0]
[2020/12/22 05:18:20 UTC] [INFO] [name=M0, stage=full, get=0, write_success=0, tps=0]
[2020/12/22 05:18:25 UTC] [INFO] [name=M0, stage=full, get=0, write_success=0, tps=0]

```
