### ISSUE TITLE
同步失败....！！！报错如下，求解决！

### ISSUE THREAD

**Issue by solemnpending** [alibaba/MongoShake#626]
[2021/08/31 11:13:02 CST] [WARN] insert docs with length[128] into ns[{tydata devidmap}] of dest mongo failed[index[0], msg[read tcp 127.0.0.1:31214->127.0.0.1:20000: i/o timeout], dup[false]]
[2021/08/31 11:13:02 CST] [CRIT] DocExecutor[80] collectionExecutor[{tydata devidmap}] sync failed: bulk run message[[{_id ObjectIdHex("5f3e38cd5a0549ab1c81e58b")} {devidmap devidmap4:e86b2589adb21d4bb7aad48973af68af} {time_create 1597913293} {user_id 827056531}]], failed[read tcp 127.0.0.1:31214->127.0.0.1:20000: i/o timeout], index[0] dup[false]

**Comment by solemnpending** [comment]
xecutor[{tydata devidmap}] sync failed: bulk run message[[{_id ObjectIdHex("5f3e38cd5a0549ab1c81e58b")} {devidmap devidmap4:e86b2589adb21d4bb7aad48973af68af} {time_create 1597913293} {user_id 827056531}]], failed[read tcp 127.0.0.1:31214->127.0.0.1:20000: i/o timeout], index[0] dup[false]
panic: DocExecutor[80] collectionExecutor[{tydata devidmap}] sync failed: bulk run message[[{_id ObjectIdHex("5f3e38cd5a0549ab1c81e58b")} {devidmap devidmap4:e86b2589adb21d4bb7aad48973af68af} {time_create 1597913293} {user_id 827056531}]], failed[read tcp 127.0.0.1:31214->127.0.0.1:20000: i/o timeout], index[0] dup[false]

goroutine 1268 [running]:
github.com/vinllen/log4go.Crashf(0xec4b1f, 0x12, 0xc0005c3f98, 0x2, 0x2)
        /Users/zhangst/language/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:46 +0xe5
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc004c46420)
        /Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:171 +0x174
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
        /Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda

**Comment by zhangst** [comment]
这个看上去是网络问题，换台机器试一试
