### ISSUE TITLE
同步数据的时候突然报错然后mongo'shake程序退出

### ISSUE THREAD

**Issue by betterxu** [alibaba/MongoShake#687]
the error like this：

[2022/01/04 16:04:58 CST] [INFO] Collector-worker-0 transfer retransmit:false send [256] logs. reply_acked [7049250198526105552[1641281461, 6096]], list_unack [0] 
[2022/01/04 16:04:58 CST] [CRIT] move chunk oplog found[{"ts":7049249966597866474,"h":691471320878684490,"v":2,"op":"i","ns":"test2.usertable","o":[{"Name":"_id","Value":"user3293434989643018416"},{"Name":"field0","Value":"OS80MEcrLCk0MFlnIip+Pk4vOz0wMDF0IFRvIjE4MzliMl49JjAwMS40MCwgOT5gJ1AlPDgiNiY2PCZkPVhlJi5uJSI6LSFyLE5vPkh1JF0rKUp/L00/IFM5LUh9L1I9N041MD0qISlwKyx8Ll95OzF4IkIpJCtyOVBnJyAqLCkuLEgrICZ8IjJmNCV6MkM1JzdgJjQuIj8sMVB7LT1gNiE+K0V5IkhjNTZmI1hhMEJzO0RxPyEuKT5uOiIoICg8KUE7MVVtOSp2LlctMkZ5OiY+NDZ4K1c3JUJjI0JxPEB9Pkx1KlZ/M1A5ICV8Jih4O0tpMy0kICIyIUchI1p7KzJ+KDx8Mk8nJTowPUovPkV7Pj4mI111O0AnPko/LC00NlR9Ly0wOjImIScgJEBxOkN5MS0kJCY6Lk8/LTxyOCE8ICMoOUlrPlM1M093PzV8PDx2IiAuNks5KDU8KDh+KiosKkY3NDF0NklnP1ZxK0Q9MDRuIlJ/PyloLC1oIkEvNkVvOlp7MzUiJVQlNisqNFk1KCY+MEp7MFItOCx2MioqKD9+KCx0KlpvLi0sLUBtISZoMy56NShyO0p7J1t1Jy1sO04rPVAlKUwtMVs5LitoIzt4PiFgIzJwOUU/IT5iKjZ+N1MxNzYmOUZrPiE0MERxIjhiOzRwPEUhJUEvMiE="}],"o2":null,"fromMigrate":true}]
[16:04:58 CST 2022/01/04] [CRIT] (github.com/alibaba/MongoShake/v2/collector.(*Batcher).filter:127) move chunk oplog found[{"ts":7049249966597866474,"h":691471320878684490,"v":2,"op":"i","ns":"test2.usertable","o":[{"Name":"_id","Value":"user3293434989643018416"},{"Name":"field0","Value":"OS80MEcrLCk0MFlnIip+Pk4vOz0wMDF0IFRvIjE4MzliMl49JjAwMS40MCwgOT5gJ1AlPDgiNiY2PCZkPVhlJi5uJSI6LSFyLE5vPkh1JF0rKUp/L00/IFM5LUh9L1I9N041MD0qISlwKyx8Ll95OzF4IkIpJCtyOVBnJyAqLCkuLEgrICZ8IjJmNCV6MkM1JzdgJjQuIj8sMVB7LT1gNiE+K0V5IkhjNTZmI1hhMEJzO0RxPyEuKT5uOiIoICg8KUE7MVVtOSp2LlctMkZ5OiY+NDZ4K1c3JUJjI0JxPEB9Pkx1KlZ/M1A5ICV8Jih4O0tpMy0kICIyIUchI1p7KzJ+KDx8Mk8nJTowPUovPkV7Pj4mI111O0AnPko/LC00NlR9Ly0wOjImIScgJEBxOkN5MS0kJCY6Lk8/LTxyOCE8ICMoOUlrPlM1M093PzV8PDx2IiAuNks5KDU8KDh+KiosKkY3NDF0NklnP1ZxK0Q9MDRuIlJ/PyloLC1oIkEvNkVvOlp7MzUiJVQlNisqNFk1KCY+MEp7MFItOCx2MioqKD9+KCx0KlpvLi0sLUBtISZoMy56NShyO0p7J1t1Jy1sO04rPVAlKUwtMVs5LitoIzt4PiFgIzJwOUU/IT5iKjZ+N1MxNzYmOUZrPiE0MERxIjhiOzRwPEUhJUEvMiE="}],"o2":null,"fromMigrate":true}]
panic: send on closed channel

goroutine 404 [running]:
github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc00039b1a0, 0xc0002db340)
	/home/rancher/go/pkg/mod/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/termlog.go:41 +0x43
github.com/vinllen/log4go.Logger.intLogf(0xc0000b45d0, 0x4, 0xef7724, 0x5b, 0xc01973fef8, 0x5, 0x5)
	/home/rancher/go/pkg/mod/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/log4go.go:223 +0x276
github.com/vinllen/log4go.Info(0xd61080, 0x11c30a0, 0xc01973fef8, 0x5, 0x5)
	/home/rancher/go/pkg/mod/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:195 +0x1b2
github.com/alibaba/MongoShake/v2/executor.(*Executor).doSync(0xc0000b8000, 0xc024e44000, 0x100, 0x100, 0x0, 0x0)
	/root/MongoShake/executor/executor.go:250 +0x2a7
github.com/alibaba/MongoShake/v2/executor.(*Executor).start(0xc0000b8000)
	/root/MongoShake/executor/executor.go:221 +0x84
created by github.com/alibaba/MongoShake/v2/executor.(*BatchGroupExecutor).Start
	/root/MongoShake/executor/executor.go:71 +0xa7

**Comment by zhangst** [comment]
源和目的MongoDB是什么版本？shake是什么版本？
请开下debug日志看下问题能否复现。

**Comment by betterxu** [comment]
> 源和目的MongoDB是什么版本？shake是什么版本？ 请开下debug日志看下问题能否复现。

源是3.4.9 目的是4.4.10，shake 是最新的。数据源是通过ycsb压入，debug显示这样

[2022/01/04 16:55:26 CST] [DEBG] writer: insert {"ts":7049249936533100181,"h":5322335860770283917,"v":2,"op":"i","ns":"test2.usertable","o":[{"Name":"_id","Value":"user5244401754933050076"},{"Name":"field0","Value":"Ozp0JjdiJid2OjxkNSNqLyYiK143NFRrJSZ2K1xjNixyK1QnKkl9KkslLTk0KDUiLkc5PUV3LlcrOSlkKz0iIE8vMih0OzcgKj80PVZhPSsuOE59MyIyJTR+PEAzLDU6O0ErLFVnJiIoOFt7JkA9PFwzNzM4OSQiPTxyP11rPU8/NDV2JyAwIE1zOFRnNjooJVIhITVwMD1sNykiJz46MCZmN1BzKyNqK1FrLkopNVJ7O0whPCAiMCRoJEcpPCJgMUkzOUAtI0E9NChmOSguIT08IzQiKCl0KVdhK1M1J0t9KisoNSokIUVlOV0lKVR3Ljd0L1k5MTkmJT88L0w5JEJ5MDQiJE4zJERlIlQ3OCsiNTlyNiF0MksxOEQtNV91N0o3LVBlMTIuMU13KlZ3Nlo3KjMwNEQjNkFrI085MVV/Iz46LU4lPTBgIihkO1Z5OUI/IFp3IU51Ni0+LTI0KVNzLyJ2M0U7IEw/NSl0LjckPEVjO1B5NlMzPiZqMkIhJCwuMVkpKCx2K1xxNVxzP0YxMjMgLE4rNigsMTQuMT4qLD1iLzNsK0NrO0RvNihkLERjNlR5Jy5yMlEzP10xNUZ1PSIiLSF4LEB5K1hlMl49LDZgKy1oKydyJEs1OT46I0lnIl47MUs7PFBpMUctITtmOjpqLkZnKkZhNigmLyM="}],"o2":null}
[2022/01/04 16:55:26 CST] [DEBG] writer: insert {"ts":7049249936533100182,"h":-2587396194273589018,"v":2,"op":"i","ns":"test2.usertable","o":[{"Name":"_id","Value":"user1444326001422250923"},{"Name":"field0","Value":"J1JzIjomI0p9M1YpOlwtOSlgOUUjLFQnIksjPTEmJ14nOEIvP0tzPlp3IUB3Ij4gJl0pJE1xLCdiIjBiOFwpNV5xNUo9OElvJChuLlY5KlZrJkt3KUU3OCt0NTI0NUZnPUx9Ljx2NTtsIyYgPiskOEkrMz10IkctKVYzLDkmKCEwOC9+JyImKEY9NC84PVBnPC12Ki14I04tLVFvNiYmMV9vMzQoJDgyNi8kJEdrNjR8IkFlLSB0O1M5JV9zNl05OkZjIk99NkQ7OF9vJks5NDUoOkJtLzMoPUF/NzI0IDsyKUxrL0ZpNz8yNiloKl8jIT4+KU07OE9/L009JDNyOydiIUNtMzY4O1whOUgnKyRmJkt3IDpiPzs8KixoPjMgO1l7Pys2MVFxPjx4MkA3LSgmIz1mOz1uM09lP0l7KSM2MT02LC9sLkRjOzIwOEIxOj1oKzIqPD9iP11/NFcnKTFkPCM+ODNyNkN7Kzw6KDEuMFFjOjQkNUZlNU5jMj9mKkUnNDJyNE9hIlk9IVUvLS9+KCQmMSgiI1J5JiN8NUVzIzd0NE5zM0BjPEp/M04nJVg1LTc2OTZsJiRwNC0yKVYrKUI/KCNoNi4qPDpqJ04lJUllOS5gNjxsIih4PyA+N0srJEspIEp/LiM2LUklNTQmOFRpJjwsPyVmLks5IDU="}],"o2":null}
[2022/01/04 16:55:26 CST] [DEBG] writer: insert {"ts":7049249936533100183,"h":2284095057412387688,"v":2,"op":"i","ns":"test2.usertable","o":[{"Name":"_id","Value":"user2386785536523171357"},{"Name":"field0","Value":"OSs0ISskOV4jOUV7PzZ0PisgO05hM0sxPD5qOkV3IEsvMUQhM1IlOUxnJ0pzOyckK1hrPzZ6LVV5O0lxIF8hLUY/NzV+Kj1oPEk5MFw/Kl19N0gjIickPVV1I1h9Ik4rNV9zM1l9Mik4ITgkNTwiKV57NjtiNlgpOlgjPVttP1VxNyEyOk8zNUtnJTkyNFgtMi9oMypsPS5uLkV5IjYoKS8+JCtgLyFyO1tnJ0N5PV51O1M5PC5sK1k9Nlh5M0ZxK1QpMFFjNkllN1JvPSMmPFttJDN6I0UnJj14Lkl7PDNsMyY4NVRlN1s7Pz86LE8nJT4qLC8oJTw8IDQgLE1/OiN6IlYjMSNqKjIkPSp4IipwOzsgK1Y1OTQwPil6PjgyPDtiMlN5IiZ+PjouPiFkMjpyN1A1LSs0N1c1OC00PEAjKVl7LE1tJkQxN1YhMVE7OCE0OFU7PEJtJ19vMlo7IDBwJVFjKi96MjxuI0M9KUN9KlMrJUpvLzYsLj0mNEg5L1pvNyI4JDFoPlQvPkk3IERhJlUrNFozLzhsPzV4OFRtKyZgKC98Nkh/LVt9Nzw+IEwtLDV+MS9+PzEkJCsoLVNlKSV8PiV4OUhjMyx+IEo9ODRwOUkxICEgMU5/L0phNlV7Pzw+Jlh/Lzd2PTUwMUYpJzMoLE0rOTt0NzV0N08="}],"o2":null}
panic: send on closed channel

goroutine 344 [running]:
github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc000286d60, 0xc01aa96500)
	/home/rancher/go/pkg/mod/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/termlog.go:41 +0x43
github.com/vinllen/log4go.Logger.intLogf(0xc0000b45d0, 0x4, 0xeed142, 0x3a, 0xc001ddbb38, 0x2, 0x2)
	/home/rancher/go/pkg/mod/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/log4go.go:223 +0x276
github.com/vinllen/log4go.Info(0xd61080, 0x11c2c90, 0xc001ddbb38, 0x2, 0x2)
	/home/rancher/go/pkg/mod/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:195 +0x1b2
github.com/alibaba/MongoShake/v2/executor.(*BulkWriter).doInsert(0xc010203da0, 0xc002fbaa40, 0x5, 0xc002fbaa46, 0x9, 0xc02abf39b0, 0xc00cf7b800, 0x100, 0x100, 0x59c301, ...)
	/root/MongoShake/executor/db_writer_bulk.go:47 +0x8b2
github.com/alibaba/MongoShake/v2/executor.(*Executor).execute(0xc0001b4d00, 0xc01587a460, 0xc00cf7b000, 0x100)
	/root/MongoShake/executor/operation.go:82 +0xe4b
github.com/alibaba/MongoShake/v2/executor.(*Executor).doSync(0xc0001b4d00, 0xc00cf7b000, 0x100, 0x100, 0x0, 0x0)
	/root/MongoShake/executor/executor.go:245 +0xfd
github.com/alibaba/MongoShake/v2/executor.(*Executor).start(0xc0001b4d00)
	/root/MongoShake/executor/executor.go:221 +0x84
created by github.com/alibaba/MongoShake/v2/executor.(*BatchGroupExecutor).Start
	/root/MongoShake/executor/executor.go:71 +0xa7

**Comment by zhangst** [comment]
你看下目的DB有数据成功写入吗？还是一条都没有成功

**Comment by betterxu** [comment]
> 你看下目的DB有数据成功写入吗？还是一条都没有成功

有成功的

**Comment by pink0520** [comment]
这个问题怎么解决呢？我也遇到了

**Comment by OneB1t** [comment]
any idea how to solve this? i think i have same issue as soon as i connect direct tunnel it keep crashing (it is working with mock tunnel type..)

EDIT: looks like development branch is not stable :-)

**Comment by zhangst** [comment]
log : move chunk oplog found
oplog field : "fromMigrate":true

For migrate from sharding to sharding. Must close balancer In source MongoDB. Otherwise, will report an error and exit.

对于Sharding到Sharding的迁移，在迁移前，一定要先关闭源库的balancer，否则很可能因为moveChunk而导致迁移报错退出

**Comment by naughtyGitCat** [comment]
> log : move chunk oplog found oplog field : "fromMigrate":true
> 
> For migrate from sharding to sharding. Must close balancer In source MongoDB. Otherwise, will report an error and exit.
> 
> 对于Sharding到Sharding的迁移，在迁移前，一定要先关闭源库的balancer，否则很可能因为moveChunk而导致迁移报错退出

After disabling the source balance setting, mongo shake panics again with the same error, is there some method to skip move chunk oplog?
