### ISSUE TITLE
mongoshake 全量同步阶段i/o timeout 不断重启

### ISSUE THREAD

**Issue by lizer2014** [alibaba/MongoShake#692]
你好， 最近有异地mongo同步的需求，在测试mongoshake遇到了这样的问题，分片集群间全量同步过程中，运行一段时间后，会有如下超时错误，然后进程重启重新同步。

Mongoshake: v2.6.5
Source mongo: v4.0.24
Target mongo: v4.0.24
Mongo type: 源端和目标端 都是 shard （3分片）

error:

```bash
- execute: "./collector.linux"
[13:10:19 CST 2022/02/11] [CRIT] (github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start:171) DocExecutor[427] collectionExecutor[{xx-ns xx-collec_test}] sync failed: bulk run message[[{_id ObjectIdHex("5e203970c143ae104c1ed098")} xxxx ]], failed[read tcp {mongoshake_ip}:38656->{dest_mongo_ip}:20400: i/o timeout], index[0] dup[false]

goroutine 3872 [running]:
github.com/vinllen/log4go.Crashf(0xec4b1f, 0x12, 0xc001ae7f98, 0x2, 0x2)
    /Users/zhangst/language/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:46 +0xe5
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc002d54120)
    /Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:171 +0x174
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
    /Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
- child process[29478] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2
```

collector.conf:
```bash
conf.version = 10

id = mongoshake

master_quorum = false

full_sync.http_port = 6101
incr_sync.http_port = 6100
system_profile_port = 6200

log.level = debug
log.dir =
log.file = collector.log
log.flush = true

sync_mode = all

mongo_urls = mongodb://{{user}}:{{password}}@{xxx}:9100,{{xxxx}}:9100,{xxx}:9100;mongodb://{{user}}:{{password}}@{xxx}:9101,{{xxxx}}:9101,{xxx}:9101;mongodb://{{user}}:{{password}}@{xxx}:9102,{{xxxx}}:9102,{xxx}:9102
mongo_cs_url = mongodb://{{user}}:{{password}}@{xxx}:8091,{{xxxx}}:8091,{xxx}:8091
mongo_s_url = mongodb://{{user}}:{{password}}@{xxx}:20100,{{xxxx}}:20100,{xxx}:20100
mongo_ssl_root_ca_file =

tunnel = direct
tunnel.address = mongodb://{{user}}:{{password}}@{xxx}:20400,{{xxxx}}:20400,{xxx}:20400
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =

mongo_connect_mode = secondaryPreferred

filter.namespace.black =
filter.namespace.white =
filter.pass.special.db =
filter.ddl_enable = true
filter.oplog.gids = false

checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file =
checkpoint.start_position = 1970-01-01T00:00:00Z

transform.namespace =

full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = shard_key

full_sync.collection_exist_drop = true

full_sync.create_index = background

full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false

incr_sync.mongo_fetch_method = change_stream

incr_sync.change_stream.watch_full_document = false

incr_sync.oplog.gids =

incr_sync.shard_key = auto
incr_sync.shard_by_object_id_whitelist =

incr_sync.worker = 8

incr_sync.tunnel.write_thread = 8

incr_sync.target_delay = 0

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none

incr_sync.executor.majority_enable = false

special.source.db.flag =
```

**Comment by zhangst** [comment]
hyverpisor用来重启异常退出的shake进程，一般用在all or incr模式同步，不用在增量同步。
日志中的报错是写入目的MongoDB失败了，需要检查下到目的MongoDB的带宽和负载情况。
bulk的写入目前对于非dup的错误都当做失败处理，这后续考虑增加下重试写入。
