### ISSUE TITLE
sync failed: duplicate key error[E11000 duplicate key error ]

### ISSUE THREAD

**Issue by AgaLiao** [alibaba/MongoShake#701]
不好意思想請問：
目前mongoshake版本為2.6.5
mongo source與target皆在Atlas上，版本都是4.0.28，6個shard
目前是以all sync去做
錯誤的部分都是因為index判定為有重複的而卡住，可是兩個document的內容是不一樣的，只有index是一樣
full_sync.executor.insert_on_dup_update這個參數嘗試著true跟false過，可是都會出問題

full_sync.executor.insert_on_dup_update＝true
```
[2022/03/28 03:20:54 CST] [WARN] insert docs with length[80] into ns[{17media UserFollowRequested}] of dest mongo failed[index[29], msg[E11000 duplicate key error collection: 17media.UserFollowRequested index: followerID_1_followeeID_1 dup key: { : "1255985c-613e-4c4c-b296-4a3ef921bc58", : "f4aa1cb1-3260-4203-a74b-693b9d8921b7" }], dup[true]]
[2022/03/28 03:20:54 CST] [WARN] dup error found, try to solve error
[2022/03/28 03:20:54 CST] [CRIT] DocExecutor[741] collectionExecutor[{17media UserFollowRequested}] sync failed: convert oplog[[{_id ObjectIdHex("5cdbf535bac953373aa0fec4")} {followerID 1255985c-613e-4c4c-b296-4a3ef921bc58} {followeeID f4aa1cb1-3260-4203-a74b-693b9d8921b7} {timestamp 1557919029} {migrated 1}]] from insert to update run failed[not found]
[03:20:54 CST 2022/03/28] [CRIT] (github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start:171) DocExecutor[741] collectionExecutor[{17media UserFollowRequested}] sync failed: convert oplog[[{_id ObjectIdHex("5cdbf535bac953373aa0fec4")} {followerID 1255985c-613e-4c4c-b296-4a3ef921bc58} {followeeID f4aa1cb1-3260-4203-a74b-693b9d8921b7} {timestamp 1557919029} {migrated 1}]] from insert to update run failed[not found]
panic: DocExecutor[741] collectionExecutor[{17media UserFollowRequested}] sync failed: convert oplog[[{_id ObjectIdHex("5cdbf535bac953373aa0fec4")} {followerID 1255985c-613e-4c4c-b296-4a3ef921bc58} {followeeID f4aa1cb1-3260-4203-a74b-693b9d8921b7} {timestamp 1557919029} {migrated 1}]] from insert to update run failed[not found]

goroutine 361838 [running]:
github.com/vinllen/log4go.Crashf(0xec4b1f, 0x12, 0xc00112ff98, 0x2, 0x2)
	/Users/zhangst/language/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:46 +0xe5
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc0012047e0)
	/Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:171 +0x174
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
	/Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
```

full_sync.executor.insert_on_dup_update=false
```
[2022/03/28 09:19:17 CST] [WARN] insert docs with length[80] into ns[{17media UserFollowRequested}] of dest mongo failed[index[29], msg[E11000 duplicate key error collection: 17media.UserFollowRequested index: followerID_1_followeeID_1 dup key: { : "1255985c-613e-4c4c-b296-4a3ef921bc58", : "f4aa1cb1-3260-4203-a74b-693b9d8921b7" }], dup[true]]
[2022/03/28 09:19:17 CST] [WARN] dup error found, try to solve error
[2022/03/28 09:19:17 CST] [CRIT] DocExecutor[740] collectionExecutor[{17media UserFollowRequested}] sync failed: duplicate key error[E11000 duplicate key error collection: 17media.UserFollowRequested index: followerID_1_followeeID_1 dup key: { : "1255985c-613e-4c4c-b296-4a3ef921bc58", : "f4aa1cb1-3260-4203-a74b-693b9d8921b7" }], you can clean the document on the target mongodb, or enable full_sync.executor.insert_on_dup_update to solve, but full-sync stage needs restart
[09:19:17 CST 2022/03/28] [CRIT] (github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start:171) DocExecutor[740] collectionExecutor[{17media UserFollowRequested}] sync failed: duplicate key error[E11000 duplicate key error collection: 17media.UserFollowRequested index: followerID_1_followeeID_1 dup key: { : "1255985c-613e-4c4c-b296-4a3ef921bc58", : "f4aa1cb1-3260-4203-a74b-693b9d8921b7" }], you can clean the document on the target mongodb, or enable full_sync.executor.insert_on_dup_update to solve, but full-sync stage needs restart
panic: DocExecutor[740] collectionExecutor[{17media UserFollowRequested}] sync failed: duplicate key error[E11000 duplicate key error collection: 17media.UserFollowRequested index: followerID_1_followeeID_1 dup key: { : "1255985c-613e-4c4c-b296-4a3ef921bc58", : "f4aa1cb1-3260-4203-a74b-693b9d8921b7" }], you can clean the document on the target mongodb, or enable full_sync.executor.insert_on_dup_update to solve, but full-sync stage needs restart

goroutine 389607 [running]:
github.com/vinllen/log4go.Crashf(0xec4b1f, 0x12, 0xc000fcff98, 0x2, 0x2)
	/Users/zhangst/language/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:46 +0xe5
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc00229b5c0)
	/Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:171 +0x174
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
	/Users/zhangst/db_code/tools/mongoshake_26/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
```

**Comment by zhangst** [comment]
convert insert to update when duplicate key found
如果_id存在在目的库，是否将insert语句修改为update语句。
full_sync.executor.insert_on_dup_update = false

这个是针对_id相同的重复记录把insert转为update，但看你提供的日志看上去是有非_id的唯一索引冲突了，followerID_1_followeeID_1，这个数据冲突需要解决下。
