### ISSUE TITLE
全量同步到4分之3，mongoshake工具报错，但是日志没有打印出报错原因，只有标准输出打印了

### ISSUE THREAD

**Issue by xiaohuazi123** [alibaba/MongoShake#755]
MongoShake的版本 ： 2.8.0
源和目的MongoDB的版本：源库是mongo3.6，目标库是mongo4.0
脱敏后的配置文件和日志
```
2022/09/08 13:05:47 CST] [INFO] [name=rpl, stage=full, get=1256837287, write_success=1256836605, tps=0]
[2022/09/08 13:05:47 CST] [INFO] Close client with mongodb://root:***@192.168.0.69:7888,192.168.0.63:7888,192.168.0.62:7888
panic: interface conversion: error is mongo.CommandError, not mongo.BulkWriteException

goroutine 18994390 [running]:
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).doSync(0xc000293710, 0xc00156a000, 0x80, 0x80, 0x0, 0x0)
/u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:225 +0x16ee
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc000293710)
/u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:169 +0xe6
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
/u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
[root@dc-web1 mongoshake]#
```

**Comment by zhangst** [comment]
develop 分支增加了错误日志的输出，请用develop分支编译再试下。
