### ISSUE TITLE
Atlas Mongodb 连接报错 panic

### ISSUE THREAD

**Issue by zouzehe** [alibaba/MongoShake#814]
* MongoDB Version:  atlas 4.4
* MongoShake Version: 2.8.2
* collect.conf [参考配置](https://github.com/alibaba/MongoShake/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%E2%80%94%E2%80%94%E5%B8%B8%E8%A7%81%E5%9C%BA%E6%99%AF%E9%85%8D%E7%BD%AE#4-%E4%BB%8E%E5%8F%AA%E6%9A%B4%E9%9C%B2mongos%E5%9C%B0%E5%9D%80%E7%9A%84mongodb%E5%88%86%E7%89%87%E9%9B%86%E7%BE%A4%E7%89%88%E5%90%8C%E6%AD%A5%E5%88%B0mongodb%E5%88%86%E7%89%87%E9%9B%86%E7%BE%A4%E7%89%88) 

`
mongo_s_url = mongodb://xxx:xxx@xxx-shard-00-00.xxx.mongodb.net:27016,xxx-shard-00-01.xxx.mongodb.net:27016,xxx-shard-00-02.xxx.mongodb.net:27016/admin?connect=direct&authSource=admin&ssl=true
mongo_ssl_root_ca_file = 
`

* 报错信息
```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b9457]

goroutine 1 [running]:
main.handleExit()
	/mnt/MongoShake-release-v2.8.2-20221215/cmd/collector/collector.go:183 +0x95
panic(0xc280a0, 0x12a16d0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/alibaba/MongoShake/v2/common.GetDBVersion(0x0, 0xe0, 0xd11540, 0x12, 0x416101)
	/mnt/MongoShake-release-v2.8.2-20221215/common/db_opertion.go:51 +0x37
main.checkConnection(0x0, 0x0)
	/mnt/MongoShake-release-v2.8.2-20221215/cmd/collector/sanitize.go:327 +0x1cc
main.SanitizeOptions(0xc00011def8, 0xc14b20)
	/mnt/MongoShake-release-v2.8.2-20221215/cmd/collector/sanitize.go:40 +0x130
main.main()
	/mnt/MongoShake-release-v2.8.2-20221215/cmd/collector/collector.go:59 +0x3c5
```

**Comment by zouzehe** [comment]
配置换成
`
mongo_s_url = mongodb://xxx:xxx@xxx-shard-00-00.xxx.mongodb.net:27016,xxx-shard-00-01.xxx.mongodb.net:27016,xxx-shard-00-02.xxx.mongodb.net:27016/admin?authSource=admin&ssl=true mongo_ssl_root_ca_file = 
`
出现这个错误，提示副本集的问题，但是atlas 配置管理没有副本集的配置
replia[mongos] not exists on startTsMap[map[]]
[08:17:00 UTC 2023/04/27] [CRIT] (main.startup:145) run replication failed: replia[mongos] not exists on startTsMap[map[]]

**Comment by zouzehe** [comment]
mongo-shake 升级到 v2.8.4 解决这个问题
