### ISSUE TITLE
crash（panic: send on closed channel）

### ISSUE THREAD

**Issue by wdbxj520** [alibaba/MongoShake#844]
version: 2.8.4 

- execute: "./collector.linux"
panic: send on closed channel

goroutine 4966 [running]:
github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc00000e1e0, 0xc0008d4b00)
    /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/termlog.g
o:41 +0x45
github.com/vinllen/log4go.Logger.intLogf(0xc00007c6f0, 0x7, 0xd881d9, 0x12, 0xc002651f98, 0x2, 0x2)
    /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/log4go.go
:223 +0x277
github.com/vinllen/log4go.Crashf(0xd881d9, 0x12, 0xc002651f98, 0x2, 0x2)
    /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.g
o:44 +0x6c
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc000486030)
    /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:172 +0x174
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
    /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
- child process[2547954] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 2

- process: "./collector.linux" exit, restart it
- execute: "./collector.linux"

**Comment by zhongli-james** [comment]
It's known bug due to third party log package: `github.com/vinllen/log4go`. when one 'LOG.Crashf()' is called, the channel in `ConsoleLogWriter` will be closed, and another try to 'LOG.xxx()' will trigger this panic issue.

We should focus on the former crash log, will fix this panic issue in next release version of mongoshake.
