### ISSUE TITLE
mongoshake-stat 执行报错

### ISSUE THREAD

**Issue by njmaojing** [alibaba/MongoShake#860]
```
[root@localhost mongo-shake-v2.8.4]# ./mongoshake-stat --port=9100
Traceback (most recent call last):
  File "./mongoshake-stat", line 36, in __get_json
    resp = urllib2.urlopen("http://%s:%s/%s" % (host, port, spec)).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
failed
[root@localhost mongo-shake-v2.8.4]# ss -ntpl|grep 9100
[root@localhost mongo-shake-v2.8.4]# ss -ntpl|grep 9101
LISTEN     0      32768       :::9101                    :::*                   users:(("collector.linux",pid=13818,fd=55))
```
9100的端口可以调用成功
 curl -s  http://127.0.0.1:9101/progress | python -m json.tool

**Comment by zhongli-james** [comment]
应该是mongoshake还没到增量阶段？
```
# http api interface. Users can use this api to monitor mongoshake.
# `curl 127.0.0.1:9100`.
# We also provide a restful tool named "mongoshake-stat" to
# print ack, lsn, checkpoint and qps information based on this api.
# usage: `./mongoshake-stat --port=9100`
# 全量和增量的restful监控端口，可以用curl查看内部监控metric统计情况。详见wiki。
full_sync.http_port = 9101
incr_sync.http_port = 9100
# profiling on net/http/profile
# profiling端口，用于查看内部go堆栈。
system_profile_port = 9200
```

代码中只有在`startOplogReplication()`中才会开启http listen。
