### ISSUE TITLE
mongodb 3.2 单节点，开启 oplog， 同步到4.4，全量加增量模式，已关闭ddl操作，但是因为ddl同步抱错

### ISSUE THREAD

**Issue by QUANTUM-0412** [alibaba/MongoShake#873]
[2024/04/27 23:41:03 CST] [CRIT] Syncer[r0] ddl oplog found[{"ts":{"T":1714207175,"I":40},"t":1,"h":-3269713082117567830,"v":2,"op":"c","ns":"logs.$cmd","o":[{"Key":"create","Value":"collection_ENTafrp"}],"o2":null$
"PrevOpTime":null}] when oplog timestamp[{1714207175 40}] less than fullSyncFinishPosition[{1714232346 11}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[18] into ns[logs.collection_ENTa0vx] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENTa0vx index: _id_ dup key: { _id: ObjectId$
'662cb7fd7f4b915630c7b77a') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [INFO] Replayer-4 Executor-4 doSync oplogRecords received[153] merged[44]. merge to 28.76% chunks
[2024/04/27 23:41:03 CST] [INFO] Collector-worker-4 transfer retransmit:false send [153] logs. reply_acked [7362463609164660761[1714207141, 25]], list_unack [0] 
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT5621] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT5621 index: _id_ dup key: { _id: ObjectId('
662cb8d47f4b915630c809f6') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[2] into ns[logs.collection_ENT1201] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT1201 index: _id_ dup key: { _id: ObjectId('
662cb9b37f4b915630c85ac2') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENTacnq] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENTacnq index: _id_ dup key: { _id: ObjectId('
662cb9aa7f4b915630c857e3') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT0914] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT0914 index: _id_ dup key: { _id: ObjectId('
662cb9be7f4b915630c85e15') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENTac1u] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENTac1u index: _id_ dup key: { _id: ObjectId('
662cb9a87f4b915630c85754') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT2400] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT2400 index: _id_ dup key: { _id: ObjectId('
662cb9b37f4b915630c85ae2') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT1599] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT1599 index: _id_ dup key: { _id: ObjectId('
662cb9b17f4b915630c85a56') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENTacpk] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENTacpk index: _id_ dup key: { _id: ObjectId('
662cb9ae7f4b915630c8596c') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[5] into ns[logs.collection_ENT6611] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT6611 index: _id_ dup key: { _id: ObjectId('
662cb8ce7f4b915630c807fc') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENTadd6] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENTadd6 index: _id_ dup key: { _id: ObjectId('
662cb9a57f4b915630c85665') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[10] into ns[logs.collection_ENT0832] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT0832 index: _id_ dup key: { _id: ObjectId(
'662cb71d7f4b915630c76977') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT2020] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT2020 index: _id_ dup key: { _id: ObjectId('
662cb9b27f4b915630c85a8b') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[4] into ns[logs.collection_ENT4262] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT4262 index: _id_ dup key: { _id: ObjectId('
662cb9b37f4b915630c85aff') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT7865] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT7865 index: _id_ dup key: { _id: ObjectId('
662cb8d67f4b915630c80abb') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[2] into ns[logs.collection_ENT2482] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT2482 index: _id_ dup key: { _id: ObjectId('
662cb9b27f4b915630c85a9e') }] res[&{0 0 0 0 0 map[]}]
[2024/04/27 23:41:03 CST] [WARN] insert docs with length[1] into ns[logs.collection_ENT0784] of dest mongo failed[E11000 duplicate key error collection: logs.collection_ENT0784 index: _id_ dup key: { _id: ObjectId('
662cb9a67f4b915630c856c1') }] res[&{0 0 0 0 0 map[]}]
panic: send on closed channel

goroutine 16513808 [running]:
github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc00028af00, 0xc01391d480)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/termlog.go:41 +0x45
github.com/vinllen/log4go.Logger.intLogf(0xc00007c6f0, 0x5, 0xdb0eb1, 0x48, 0xc000a7dbb8, 0x4, 0x4)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/log4go.go:223 +0x277
github.com/vinllen/log4go.Warn(0xc516e0, 0xf02660, 0xc000a7dbb8, 0x4, 0x4, 0xc08ed88a45, 0x12)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:215 +0x46c
github.com/alibaba/MongoShake/v2/executor.(*BulkWriter).doInsert(0xc04414bc80, 0xc08ed88a40, 0x4, 0xc08ed88a45, 0x12, 0xc01443a5a0, 0xc03e999890, 0x2, 0x2, 0x203000, ...)
        /u02/shuntong.zhang/db_src/MongoShake/executor/db_writer_bulk.go:38 +0x5e5
github.com/alibaba/MongoShake/v2/executor.(*Executor).execute(0xc000012340, 0xc012b8b9a0, 0x0, 0x0)
        /u02/shuntong.zhang/db_src/MongoShake/executor/operation.go:87 +0xe4f
github.com/alibaba/MongoShake/v2/executor.(*Executor).doSync(0xc000012340, 0xc0c8f7fc00, 0x63, 0x80, 0x0, 0x0)
        /u02/shuntong.zhang/db_src/MongoShake/executor/executor.go:252 +0x1c8
github.com/alibaba/MongoShake/v2/executor.(*Executor).start(0xc000012340)
        /u02/shuntong.zhang/db_src/MongoShake/executor/executor.go:220 +0x85
created by github.com/alibaba/MongoShake/v2/executor.(*BatchGroupExecutor).Start
        /u02/shuntong.zhang/db_src/MongoShake/executor/executor.go:70 +0xa7

**Comment by ilaotan** [comment]
报错里不是写了吗 发现ddl语句 "ns":"logs.$cmd","o":[{"Key":"create","Value":"collection_ENTafrp"}],"o2":null$
"PrevOpTime":null}]    你不应该排查为什么会出ddl吗？

**Comment by zhongli-james** [comment]
从代码来看这里的报错是符合预期的。
代表全量同步期间遇到了非预期的DDL（oplog的`ts`小于`fullSyncFinishPosition`）
<img width="906" alt="Image" src="https://github.com/user-attachments/assets/3b149c16-c387-4979-9956-81edd898d4fa" />
这里也没有检查filter.ddl_enable参数是否为false，就直接报错并crash了。

临时的workaround：等没有建表的DDL时重新all模式同步一遍
